<Project>
  <Import Project="../../Directory.Packages.props" />
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RunicCommandLineVersion Condition="'$(RunicCommandLineVersion)' == ''">1.0.0-preview.1</RunicCommandLineVersion>
    <RunicDesktopVersion Condition="'$(RunicDesktopVersion)' == ''">1.0.0-preview.1</RunicDesktopVersion>
  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>
</Project>
