<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Runic.CommandLine" Version="1.0.0-preview.1" />
    <PackageVersion Include="Runic.Desktop" Version="1.0.0-preview.1" />
  </ItemGroup>
</Project>
