<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../eng/build/desktop.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="windows-loopback.cs" />
    <ProjectReference Include="../../../packages/dotnet/Runic.Desktop/Runic.Desktop.csproj" />
    <ProjectReference Include="../../../packages/dotnet/Runic.Platform.Runtime/Runic.Platform.Runtime.csproj" />
    <ProjectReference Include="../../../packages/dotnet/Runic.Platform.Windows/Runic.Platform.Windows.csproj" />
  </ItemGroup>
</Project>
