<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <RunicAssetsDist>$(MSBuildProjectDirectory)/vite-dist</RunicAssetsDist>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RunicAssets" Version="$(RunicAssetsPackageVersion)" />
    <PackageReference Include="RunicAssets.CsWebUi" Version="$(RunicAssetsPackageVersion)" />
    <PackageReference Include="RunicAssets.RunicToolkit" Version="$(RunicAssetsPackageVersion)" />
  </ItemGroup>
</Project>
