// <auto-generated />
import { Schema } from "effect";
import { bridge, defineApplicationBridgeContract, materializeApplicationBridgeContract } from "@runic-artifex/application-bridge";

export type IncrementCounter = { readonly "_tag": "IncrementCounter"; readonly "step": number; };
export const IncrementCounter: Schema.Schema<IncrementCounter> = Schema.Struct({ "_tag": Schema.Literal("IncrementCounter"), "step": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(1), Schema.lessThanOrEqualTo(10)) }).annotations({ identifier: "IncrementCounter" });
export type IncrementCounterEncoded = Schema.Schema.Encoded<typeof IncrementCounter>;

export type ResetCounter = { readonly "_tag": "ResetCounter"; };
export const ResetCounter: Schema.Schema<ResetCounter> = Schema.Struct({ "_tag": Schema.Literal("ResetCounter") }).annotations({ identifier: "ResetCounter" });
export type ResetCounterEncoded = Schema.Schema.Encoded<typeof ResetCounter>;

export type CounterChanged = { readonly "_tag": "CounterChanged"; readonly "snapshot": CounterSnapshot; };
export const CounterChanged: Schema.Schema<CounterChanged> = Schema.Struct({ "_tag": Schema.Literal("CounterChanged"), "snapshot": Schema.suspend(() => CounterSnapshot) }).annotations({ identifier: "CounterChanged" });
export type CounterChangedEncoded = Schema.Schema.Encoded<typeof CounterChanged>;

export type CounterIncremented = { readonly "_tag": "CounterIncremented"; readonly "snapshot": CounterSnapshot; };
export const CounterIncremented: Schema.Schema<CounterIncremented> = Schema.Struct({ "_tag": Schema.Literal("CounterIncremented"), "snapshot": Schema.suspend(() => CounterSnapshot) }).annotations({ identifier: "CounterIncremented" });
export type CounterIncrementedEncoded = Schema.Schema.Encoded<typeof CounterIncremented>;

export type CounterReset = { readonly "_tag": "CounterReset"; readonly "snapshot": CounterSnapshot; };
export const CounterReset: Schema.Schema<CounterReset> = Schema.Struct({ "_tag": Schema.Literal("CounterReset"), "snapshot": Schema.suspend(() => CounterSnapshot) }).annotations({ identifier: "CounterReset" });
export type CounterResetEncoded = Schema.Schema.Encoded<typeof CounterReset>;

export type CounterSnapshot = { readonly "count": number; readonly "history": ReadonlyArray<number>; readonly "revision": number; };
export const CounterSnapshot: Schema.Schema<CounterSnapshot> = Schema.Struct({ "count": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(-2147483648), Schema.lessThanOrEqualTo(2147483647)), "history": Schema.Array(Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(-2147483648), Schema.lessThanOrEqualTo(2147483647))), "revision": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(0), Schema.lessThanOrEqualTo(9007199254740991)) }).annotations({ identifier: "CounterSnapshot" });
export type CounterSnapshotEncoded = Schema.Schema.Encoded<typeof CounterSnapshot>;

const definition = defineApplicationBridgeContract({
  protocol: {"identity":"runic.artifex.counter","version":1},
  csharp: {"contractName":"Counter","namespace":"Runic.Application.Generated"},
  snapshot: CounterSnapshot,
  commands: [
    bridge.command(IncrementCounter, { receipt: CounterIncremented, startsOperation: false, cancellable: false, advancesRevision: true }),
    bridge.command(ResetCounter, { receipt: CounterReset, startsOperation: false, cancellable: false, advancesRevision: true }),
  ],
  events: [CounterChanged],
  errors: [],
});
export const applicationBridge = materializeApplicationBridgeContract(definition, "58a0dda63c7e4b41ebce179913af55c0e53b5d17d627e8fd7116da40414a11d5");
export type CounterCommand = Schema.Schema.Type<typeof applicationBridge.command>;
export type CounterReceipt = Schema.Schema.Type<typeof applicationBridge.receipt>;
export type CounterEvent = Schema.Schema.Type<typeof applicationBridge.event>;
export default applicationBridge;
