<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../eng/build/assets.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicAssetsDefaultTargetFramework)</TargetFramework>
    <AssemblyName>Runic.Assets.Desktop.Tests</AssemblyName>
    <RootNamespace>Runic.Assets.Desktop.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../packages/dotnet/Runic.Assets.Desktop/Runic.Assets.Desktop.csproj" />
  </ItemGroup>
  <Import Project="../../../eng/build/assets.targets" />
</Project>
