<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../../eng/build/application.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Runic.Application.Bridge.PostMvvmDiscovery.Tests</AssemblyName>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Reflection.MetadataLoadContext" />
  </ItemGroup>
  <Import Project="../../../eng/build/application.targets" />
</Project>
