<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup>
    <ProjectReference Include="../Domain/CustomerDomain.csproj" />
    <ProjectReference Include="../../../../packages/runic-toolkit/src/Runic.Application.Bridge/Runic.Application.Bridge.csproj" />
    <ProjectReference Include="../../../../packages/runic-toolkit/src/Runic.Application.Bridge.Generators/Runic.Application.Bridge.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
  <Import Project="../../../../packages/runic-toolkit/src/Runic.Application.Bridge/buildTransitive/Runic.Application.Bridge.targets" />
</Project>
