using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;

namespace Runic.Assets;

/// <summary>Reads and writes the portable Runic Assets ZIP archive format.</summary>
public static class AssetArchive
{
    /// <summary>The archive contract written to <c>runic-assets.json</c>.</summary>
    public const string CurrentVersion = "runic.assets.archive/1";

    /// <summary>The default manifest-resource name generated by Runic Assets' build target.</summary>
    public const string DefaultResourceName = "Runic.Assets.StaticFiles";

    private const string ManifestEntryName = "runic-assets.json";
    private const string ContentPrefix = "assets/";
    private static readonly DateTimeOffset StableTimestamp = new(1980, 1, 1, 0, 0, 0, TimeSpan.Zero);

    /// <summary>Writes a deterministic, portable ZIP archive from one validated source.</summary>
    public static async ValueTask WriteAsync(
        IAssetSource source,
        Stream destination,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(destination);
        if (!destination.CanWrite)
        {
            throw new ArgumentException("The archive destination must be writable.", nameof(destination));
        }

        AssetManifest manifest = source.Manifest;
        await source.ValidateAsync(cancellationToken).ConfigureAwait(false);
        using var archive = new ZipArchive(destination, ZipArchiveMode.Create, leaveOpen: true);
        await WriteManifestAsync(archive, manifest, cancellationToken).ConfigureAwait(false);

        foreach (AssetDescriptor descriptor in manifest.Assets)
        {
            cancellationToken.ThrowIfCancellationRequested();
            ZipArchiveEntry contentEntry = archive.CreateEntry(
                ContentPrefix + descriptor.RelativePath,
                IsAlreadyCompressed(descriptor.RelativePath)
                    ? CompressionLevel.NoCompression
                    : CompressionLevel.SmallestSize);
            contentEntry.LastWriteTime = StableTimestamp;
            await using Stream output = contentEntry.Open();
            await using Stream input = await source
                .OpenReadAsync(descriptor.RelativePath, cancellationToken)
                .ConfigureAwait(false);
            await CopyAndVerifyAsync(input, output, descriptor, cancellationToken).ConfigureAwait(false);
        }
    }

    /// <summary>
    /// Writes a canonical archive from a local directory using the same manifest, validation,
    /// media-type, cache, and ZIP writer authority as every other archive producer.
    /// </summary>
    [System.Runtime.Versioning.SupportedOSPlatform("linux")]
    public static async ValueTask WriteDirectoryAsync(
        string sourceDirectory,
        Stream destination,
        string entryPointRelativePath = "index.html",
        IEnumerable<string>? excludedPaths = null,
        CancellationToken cancellationToken = default)
    {
        using var source = new DirectoryArchiveSource(
            sourceDirectory,
            entryPointRelativePath,
            excludedPaths,
            cancellationToken);
        await WriteAsync(source, destination, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Writes a canonical archive from a directory generated earlier in the same trusted build.
    /// This snapshot rejects observed links but is not safe against concurrent hostile mutation.
    /// </summary>
    internal static async ValueTask WriteTrustedGeneratedOutputDirectoryAsync(
        string sourceDirectory,
        Stream destination,
        string entryPointRelativePath = "index.html",
        IEnumerable<string>? excludedPaths = null,
        CancellationToken cancellationToken = default)
    {
        var source = new TrustedGeneratedOutputDirectorySource(
            sourceDirectory,
            entryPointRelativePath,
            excludedPaths,
            cancellationToken);
        await WriteAsync(source, destination, cancellationToken).ConfigureAwait(false);
    }

    /// <summary>Loads and validates a portable Runic Assets archive into memory.</summary>
    public static AssetArchiveSource Read(Stream source, AssetArchiveReadOptions? options = null)
        => ReadCore(source, options, CancellationToken.None);

    private static AssetArchiveSource ReadCore(
        Stream source,
        AssetArchiveReadOptions? options,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(source);
        if (!source.CanRead)
        {
            throw new ArgumentException("The archive source must be readable.", nameof(source));
        }

        options ??= new AssetArchiveReadOptions();
        ValidateReadOptions(options);

        using var copy = new MemoryStream();
        CopyBounded(source, copy, options.MaxArchiveBytes, cancellationToken);
        copy.Position = 0;
        using var archive = new ZipArchive(copy, ZipArchiveMode.Read, leaveOpen: false);
        var entries = new Dictionary<string, ZipArchiveEntry>(StringComparer.Ordinal);
        foreach (ZipArchiveEntry entry in archive.Entries)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (entry.FullName.EndsWith('/'))
            {
                continue;
            }

            if (!entries.TryAdd(entry.FullName, entry))
            {
                throw new InvalidDataException($"The asset archive contains duplicate entry '{entry.FullName}'.");
            }
        }

        if (!entries.Remove(ManifestEntryName, out ZipArchiveEntry? manifestEntry))
        {
            throw new InvalidDataException("The asset archive does not contain runic-assets.json.");
        }

        AssetDescriptor[] descriptors;
        using (Stream manifestStream = manifestEntry.Open())
        using (var manifestCopy = new MemoryStream())
        {
            if (manifestEntry.Length > options.MaxManifestBytes)
            {
                throw new InvalidDataException(
                    $"The asset archive manifest exceeds the {options.MaxManifestBytes} byte limit.");
            }

            CopyBounded(manifestStream, manifestCopy, options.MaxManifestBytes, cancellationToken);
            manifestCopy.Position = 0;
            cancellationToken.ThrowIfCancellationRequested();
            using JsonDocument document = ParseManifest(manifestCopy);
            cancellationToken.ThrowIfCancellationRequested();
            JsonElement root = document.RootElement;
            if (root.ValueKind != JsonValueKind.Object
                || !root.TryGetProperty("version", out JsonElement version)
                || !StringComparer.Ordinal.Equals(version.GetString(), CurrentVersion)
                || !root.TryGetProperty("assets", out JsonElement assets)
                || assets.ValueKind != JsonValueKind.Array)
            {
                throw new InvalidDataException("The asset archive manifest has an unsupported shape or version.");
            }

            var parsed = new List<AssetDescriptor>();
            long totalLength = 0;
            foreach (JsonElement asset in assets.EnumerateArray())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (parsed.Count >= options.MaxFileCount)
                {
                    throw new InvalidDataException(
                        $"The asset archive exceeds the {options.MaxFileCount} file limit.");
                }

                try
                {
                    var descriptor = new AssetDescriptor(
                        asset.GetProperty("path").GetString()!,
                        asset.GetProperty("mediaType").GetString()!,
                        asset.GetProperty("length").GetInt64(),
                        asset.GetProperty("sha256").GetString()!,
                        asset.GetProperty("entryPoint").GetBoolean(),
                        Enum.Parse<AssetCacheMode>(asset.GetProperty("cacheMode").GetString()!, ignoreCase: false));
                    if (descriptor.Length > options.MaxTotalUncompressedBytes - totalLength)
                    {
                        throw new InvalidDataException(
                            $"The asset archive exceeds the {options.MaxTotalUncompressedBytes} byte uncompressed-size limit.");
                    }

                    totalLength += descriptor.Length;
                    parsed.Add(descriptor);
                }
                catch (Exception exception) when (exception is ArgumentException or FormatException or InvalidOperationException or KeyNotFoundException)
                {
                    throw new InvalidDataException("The asset archive manifest contains invalid asset metadata.", exception);
                }
            }

            descriptors = parsed.ToArray();
        }

        var content = new Dictionary<string, byte[]>(StringComparer.Ordinal);
        foreach (AssetDescriptor descriptor in descriptors)
        {
            cancellationToken.ThrowIfCancellationRequested();
            string entryName = ContentPrefix + descriptor.RelativePath;
            if (!entries.Remove(entryName, out ZipArchiveEntry? entry))
            {
                throw new InvalidDataException($"The asset archive is missing '{descriptor.RelativePath}'.");
            }

            if (entry.Length != descriptor.Length || entry.Length > int.MaxValue)
            {
                throw new InvalidDataException($"Asset '{descriptor.RelativePath}' has an unexpected length.");
            }

            using Stream input = entry.Open();
            using var output = new MemoryStream(checked((int)entry.Length));
            CopyBounded(input, output, descriptor.Length, cancellationToken);
            byte[] bytes = output.ToArray();
            using var validation = new MemoryStream(bytes, writable: false);
            AssetHashing.Verify(descriptor, validation);
            content.Add(descriptor.RelativePath, bytes);
        }

        if (entries.Count != 0)
        {
            throw new InvalidDataException("The asset archive contains undeclared files.");
        }

        return new AssetArchiveSource(new AssetManifest(descriptors), content);
    }

    /// <summary>Loads a canonical Runic Assets archive from an assembly manifest resource.</summary>
    public static AssetArchiveSource ReadEmbedded(
        Assembly assembly,
        string resourceName = DefaultResourceName,
        AssetArchiveReadOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(assembly);
        ArgumentException.ThrowIfNullOrWhiteSpace(resourceName);

        using Stream stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new ArgumentException(
                $"Assembly '{assembly.GetName().Name}' does not contain manifest resource '{resourceName}'.",
                nameof(resourceName));
        return Read(stream, options);
    }

    /// <summary>Validates an archive and returns its canonical, deterministic manifest inspection.</summary>
    public static AssetArchiveInspection Inspect(Stream source, AssetArchiveReadOptions? options = null)
    {
        AssetArchiveSource archive = ReadCore(source, options, CancellationToken.None);
        return new AssetArchiveInspection(archive.Manifest, SerializeManifest(archive.Manifest));
    }

    /// <summary>Returns the schema compatibility and migration decision for a validated archive.</summary>
    public static AssetArchiveCompatibilityReport GetCompatibilityReport(
        Stream source,
        AssetArchiveReadOptions? options = null) =>
        new(Inspect(source, options));

    /// <summary>
    /// Validates and copies an archive through the current migration boundary. Schema 1 is retained,
    /// so a compatible archive is copied byte-for-byte without rewriting its manifest or content.
    /// </summary>
    public static async ValueTask<AssetArchiveCompatibilityReport> MigrateAsync(
        Stream source,
        Stream destination,
        AssetArchiveReadOptions? options = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(source);
        ArgumentNullException.ThrowIfNull(destination);
        if (!source.CanRead)
        {
            throw new ArgumentException("The migration source must be readable.", nameof(source));
        }
        if (!destination.CanWrite)
        {
            throw new ArgumentException("The migration destination must be writable.", nameof(destination));
        }

        if (ReferenceEquals(source, destination))
        {
            throw new ArgumentException("Migration source and destination must be different streams.", nameof(destination));
        }

        options ??= new AssetArchiveReadOptions();
        ValidateReadOptions(options);
        long? sourcePosition = source.CanSeek ? source.Position : null;
        long? destinationPosition = destination.CanSeek ? destination.Position : null;
        try
        {
            using var buffered = new MemoryStream();
            await CopyBoundedAsync(source, buffered, options.MaxArchiveBytes, cancellationToken)
                .ConfigureAwait(false);
            byte[] bytes = buffered.ToArray();
            using var validation = new MemoryStream(bytes, writable: false);
            AssetArchiveSource archive = ReadCore(validation, options, cancellationToken);
            var inspection = new AssetArchiveInspection(archive.Manifest, SerializeManifest(archive.Manifest));
            var report = new AssetArchiveCompatibilityReport(inspection);
            cancellationToken.ThrowIfCancellationRequested();
            await destination.WriteAsync(bytes, cancellationToken).ConfigureAwait(false);
            return report;
        }
        finally
        {
            if (sourcePosition is long sourceOffset)
            {
                source.Position = sourceOffset;
            }

            if (destinationPosition is long destinationOffset)
            {
                destination.Position = destinationOffset;
            }
        }
    }

    private static async ValueTask WriteManifestAsync(
        ZipArchive archive,
        AssetManifest manifest,
        CancellationToken cancellationToken)
    {
        ZipArchiveEntry manifestEntry = archive.CreateEntry(ManifestEntryName, CompressionLevel.SmallestSize);
        manifestEntry.LastWriteTime = StableTimestamp;
        await using Stream manifestStream = manifestEntry.Open();
        using var writer = new Utf8JsonWriter(manifestStream, new JsonWriterOptions { Indented = false });
        WriteManifest(writer, manifest);
        await writer.FlushAsync(cancellationToken).ConfigureAwait(false);
    }

    private static void WriteManifest(Utf8JsonWriter writer, AssetManifest manifest)
    {
        writer.WriteStartObject();
        writer.WriteString("version", CurrentVersion);
        writer.WriteStartArray("assets");
        foreach (AssetDescriptor descriptor in manifest.Assets)
        {
            writer.WriteStartObject();
            writer.WriteString("path", descriptor.RelativePath);
            writer.WriteString("mediaType", descriptor.MediaType);
            writer.WriteNumber("length", descriptor.Length);
            writer.WriteString("sha256", descriptor.Sha256);
            writer.WriteBoolean("entryPoint", descriptor.IsEntryPoint);
            writer.WriteString("cacheMode", descriptor.CacheMode.ToString());
            writer.WriteEndObject();
        }

        writer.WriteEndArray();
        writer.WriteEndObject();
    }

    private static byte[] SerializeManifest(AssetManifest manifest)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = false }))
        {
            WriteManifest(writer, manifest);
        }

        return stream.ToArray();
    }

    private static bool IsAlreadyCompressed(string path) =>
        Path.GetExtension(path).ToLowerInvariant() is
            ".7z" or ".avif" or ".br" or ".gif" or ".gz" or ".ico" or ".jpeg" or ".jpg"
            or ".mp3" or ".mp4" or ".ogg" or ".opus" or ".pdf" or ".png" or ".rar"
            or ".webm" or ".webp" or ".woff" or ".woff2" or ".zip";

    private static JsonDocument ParseManifest(Stream source)
    {
        try
        {
            return JsonDocument.Parse(source);
        }
        catch (JsonException exception)
        {
            throw new InvalidDataException("The asset archive manifest is not valid JSON.", exception);
        }
    }

    private static void ValidateReadOptions(AssetArchiveReadOptions options)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(options.MaxFileCount, 1);
        ArgumentOutOfRangeException.ThrowIfLessThan(options.MaxArchiveBytes, 1);
        ArgumentOutOfRangeException.ThrowIfLessThan(options.MaxTotalUncompressedBytes, 1);
        ArgumentOutOfRangeException.ThrowIfLessThan(options.MaxManifestBytes, 1);
    }

    private static async ValueTask CopyAndVerifyAsync(
        Stream input,
        Stream output,
        AssetDescriptor descriptor,
        CancellationToken cancellationToken)
    {
        using IncrementalHash hash = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);
        byte[] buffer = new byte[81_920];
        long total = 0;
        int read;
        while ((read = await input.ReadAsync(buffer.AsMemory(), cancellationToken).ConfigureAwait(false)) != 0)
        {
            if (read > descriptor.Length - total)
            {
                throw new InvalidDataException($"Asset '{descriptor.RelativePath}' exceeded its declared length.");
            }

            hash.AppendData(buffer, 0, read);
            await output.WriteAsync(buffer.AsMemory(0, read), cancellationToken).ConfigureAwait(false);
            total += read;
        }

        if (total != descriptor.Length
            || !StringComparer.Ordinal.Equals(
                Convert.ToHexStringLower(hash.GetHashAndReset()),
                descriptor.Sha256))
        {
            throw new InvalidDataException($"Asset '{descriptor.RelativePath}' changed while its archive was written.");
        }
    }

    private static void CopyBounded(
        Stream source,
        Stream destination,
        long maximumBytes,
        CancellationToken cancellationToken)
    {
        byte[] buffer = new byte[81_920];
        long total = 0;
        int read;
        while ((read = source.Read(buffer, 0, buffer.Length)) != 0)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (read > maximumBytes - total)
            {
                throw new InvalidDataException(
                    $"The asset archive exceeds the {maximumBytes} byte archive-size limit.");
            }

            destination.Write(buffer, 0, read);
            total += read;
        }
    }

    private static async ValueTask CopyBoundedAsync(
        Stream source,
        Stream destination,
        long maximumBytes,
        CancellationToken cancellationToken)
    {
        byte[] buffer = new byte[81_920];
        long total = 0;
        int read;
        while ((read = await source.ReadAsync(buffer.AsMemory(), cancellationToken).ConfigureAwait(false)) != 0)
        {
            if (read > maximumBytes - total)
            {
                throw new InvalidDataException(
                    $"The asset archive exceeds the {maximumBytes} byte archive-size limit.");
            }

            await destination.WriteAsync(buffer.AsMemory(0, read), cancellationToken).ConfigureAwait(false);
            total += read;
        }
    }

    [System.Runtime.Versioning.SupportedOSPlatform("linux")]
    private sealed class DirectoryArchiveSource : IAssetSource, IDisposable
    {
        private readonly LinuxAssetRoot _root;
        private readonly HashSet<string> _excludedPaths;

        internal DirectoryArchiveSource(
            string sourceDirectory,
            string entryPointRelativePath,
            IEnumerable<string>? excludedPaths,
            CancellationToken cancellationToken)
        {
            if (!OperatingSystem.IsLinux())
            {
                throw new PlatformNotSupportedException(
                    "Directory archive compilation is supported on Linux only because it requires no-follow directory handles.");
            }

            ArgumentException.ThrowIfNullOrWhiteSpace(sourceDirectory);
            _root = new LinuxAssetRoot(Path.GetFullPath(sourceDirectory));
            string entryPoint = AssetPath.Normalize(entryPointRelativePath);
            _excludedPaths = new HashSet<string>(StringComparer.Ordinal);
            if (excludedPaths is not null)
            {
                foreach (string excludedPath in excludedPaths)
                {
                    _excludedPaths.Add(AssetPath.Normalize(excludedPath));
                }
            }

            try
            {
                Manifest = Scan(entryPoint, cancellationToken);
            }
            catch
            {
                _root.Dispose();
                throw;
            }
        }

        public AssetManifest Manifest { get; }

        public ValueTask ValidateAsync(CancellationToken cancellationToken = default)
        {
            foreach (AssetDescriptor descriptor in Manifest.Assets)
            {
                cancellationToken.ThrowIfCancellationRequested();
                using FileStream stream = OpenFile(descriptor.RelativePath);
                AssetHashing.Verify(descriptor, stream);
            }

            return ValueTask.CompletedTask;
        }

        public ValueTask<Stream> OpenReadAsync(
            string relativePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            string path = AssetPath.Normalize(relativePath);
            if (!Manifest.TryGetAsset(path, out _))
            {
                throw new FileNotFoundException("The requested asset is not declared by the archive manifest.", path);
            }

            return ValueTask.FromResult<Stream>(OpenFile(path));
        }

        public void Dispose() => _root.Dispose();

        private AssetManifest Scan(string entryPoint, CancellationToken cancellationToken)
        {
            var descriptors = new List<AssetDescriptor>();
            var pending = new Stack<string>();
            pending.Push("");
            while (pending.Count != 0)
            {
                cancellationToken.ThrowIfCancellationRequested();
                string directory = pending.Pop();
                foreach (string name in _root.EnumerateEntries(directory))
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    string relativePath = directory.Length == 0 ? name : directory + "/" + name;
                    relativePath = AssetPath.Normalize(relativePath);
                    if (_root.IsDirectory(relativePath))
                    {
                        pending.Push(relativePath);
                        continue;
                    }

                    if (_excludedPaths.Contains(relativePath))
                    {
                        continue;
                    }

                    using FileStream stream = OpenFile(relativePath);
                    descriptors.Add(AssetHashing.Describe(
                        relativePath,
                        stream,
                        mediaType: null,
                        StringComparer.Ordinal.Equals(relativePath, entryPoint),
                        relativePath.EndsWith(".html", StringComparison.OrdinalIgnoreCase)
                            ? AssetCacheMode.Revalidate
                            : AssetCacheMode.Immutable));
                }
            }

            return new AssetManifest(descriptors);
        }

        private FileStream OpenFile(string relativePath)
        {
            return _root.OpenRead(AssetPath.Normalize(relativePath));
        }
    }

    private sealed class TrustedGeneratedOutputDirectorySource : IAssetSource
    {
        private readonly Dictionary<string, byte[]> _contents;

        internal TrustedGeneratedOutputDirectorySource(
            string sourceDirectory,
            string entryPointRelativePath,
            IEnumerable<string>? excludedPaths,
            CancellationToken cancellationToken)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(sourceDirectory);
            string root = Path.GetFullPath(sourceDirectory);
            var rootInfo = new DirectoryInfo(root);
            if (!rootInfo.Exists)
            {
                throw new DirectoryNotFoundException($"Asset source directory '{root}' does not exist.");
            }

            ThrowIfLink(rootInfo);
            string entryPoint = AssetPath.Normalize(entryPointRelativePath);
            var excluded = new HashSet<string>(StringComparer.Ordinal);
            if (excludedPaths is not null)
            {
                foreach (string excludedPath in excludedPaths)
                {
                    excluded.Add(AssetPath.Normalize(excludedPath));
                }
            }

            _contents = Scan(rootInfo, entryPoint, excluded, cancellationToken, out AssetManifest manifest);
            Manifest = manifest;
        }

        public AssetManifest Manifest { get; }

        public ValueTask ValidateAsync(CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            return ValueTask.CompletedTask;
        }

        public ValueTask<Stream> OpenReadAsync(
            string relativePath,
            CancellationToken cancellationToken = default)
        {
            cancellationToken.ThrowIfCancellationRequested();
            string path = AssetPath.Normalize(relativePath);
            if (!Manifest.TryGetAsset(path, out _))
            {
                throw new FileNotFoundException("The requested asset is not declared by the archive manifest.", path);
            }

            return ValueTask.FromResult<Stream>(new MemoryStream(_contents[path], writable: false));
        }

        private static Dictionary<string, byte[]> Scan(
            DirectoryInfo root,
            string entryPoint,
            HashSet<string> excluded,
            CancellationToken cancellationToken,
            out AssetManifest manifest)
        {
            var descriptors = new List<AssetDescriptor>();
            var contents = new Dictionary<string, byte[]>(StringComparer.Ordinal);
            var pending = new Stack<DirectoryInfo>();
            pending.Push(root);
            while (pending.Count != 0)
            {
                cancellationToken.ThrowIfCancellationRequested();
                DirectoryInfo directory = pending.Pop();
                foreach (FileSystemInfo entry in directory.GetFileSystemInfos())
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    ThrowIfLink(entry);
                    if (entry is DirectoryInfo childDirectory)
                    {
                        pending.Push(childDirectory);
                        continue;
                    }

                    if (entry is not FileInfo file)
                    {
                        throw new InvalidDataException(
                            $"Asset directory entry '{entry.FullName}' is not a regular file.");
                    }

                    string relativePath = ToAssetPath(root.FullName, file.FullName);
                    if (excluded.Contains(relativePath))
                    {
                        continue;
                    }

                    byte[] content = File.ReadAllBytes(file.FullName);
                    ThrowIfLink(new FileInfo(file.FullName));
                    using var stream = new MemoryStream(content, writable: false);
                    descriptors.Add(AssetHashing.Describe(
                        relativePath,
                        stream,
                        mediaType: null,
                        StringComparer.Ordinal.Equals(relativePath, entryPoint),
                        relativePath.EndsWith(".html", StringComparison.OrdinalIgnoreCase)
                            ? AssetCacheMode.Revalidate
                            : AssetCacheMode.Immutable));
                    contents.Add(relativePath, content);
                }
            }

            manifest = new AssetManifest(descriptors);
            return contents;
        }

        private static string ToAssetPath(string root, string path)
        {
            string relative = Path.GetRelativePath(root, path)
                .Replace(Path.DirectorySeparatorChar, '/')
                .Replace(Path.AltDirectorySeparatorChar, '/');
            return AssetPath.Normalize(relative);
        }

        private static void ThrowIfLink(FileSystemInfo entry)
        {
            if ((entry.Attributes & FileAttributes.ReparsePoint) != 0 || entry.LinkTarget is not null)
            {
                throw new InvalidDataException(
                    "Trusted generated asset output cannot contain symbolic links or reparse points.");
            }
        }
    }
}

/// <summary>A deterministic, validated description of a Runic Assets archive.</summary>
public sealed class AssetArchiveInspection
{
    private readonly string _archiveVersion;

    internal AssetArchiveInspection(AssetManifest manifest, byte[] canonicalManifest)
    {
        Manifest = manifest ?? throw new ArgumentNullException(nameof(manifest));
        ManifestSha256 = Convert.ToHexStringLower(SHA256.HashData(canonicalManifest));
        _archiveVersion = AssetArchive.CurrentVersion;
    }

    /// <summary>Gets the retained archive schema identifier.</summary>
    public string ArchiveVersion => _archiveVersion;

    /// <summary>Gets the validated, immutable manifest owned by the archive.</summary>
    public AssetManifest Manifest { get; }

    /// <summary>Gets the SHA-256 digest of the archive's canonical manifest bytes.</summary>
    public string ManifestSha256 { get; }

    /// <summary>Writes a line-oriented report with deterministic field and asset ordering.</summary>
    public string ToDeterministicReport()
    {
        var report = new StringBuilder();
        report.Append("archiveVersion=").Append(ArchiveVersion).Append('\n');
        report.Append("manifestVersion=").Append(Manifest.Version).Append('\n');
        report.Append("manifestSha256=").Append(ManifestSha256).Append('\n');
        report.Append("assetCount=").Append(Manifest.Assets.Count).Append('\n');
        report.Append("entryPoint=").Append(Manifest.EntryPoint.RelativePath).Append('\n');
        foreach (AssetDescriptor asset in Manifest.Assets)
        {
            report.Append("asset=")
                .Append(asset.RelativePath).Append('|')
                .Append(asset.MediaType).Append('|')
                .Append(asset.Length).Append('|')
                .Append(asset.Sha256).Append('|')
                .Append(asset.IsEntryPoint ? "entry" : "content").Append('|')
                .Append(asset.CacheMode).Append('\n');
        }

        return report.ToString();
    }
}

/// <summary>Reports whether an archive needs a schema migration for this reader.</summary>
public sealed class AssetArchiveCompatibilityReport
{
    private readonly bool _isCompatible;
    private readonly string _migrationAction;

    internal AssetArchiveCompatibilityReport(AssetArchiveInspection inspection)
    {
        Inspection = inspection ?? throw new ArgumentNullException(nameof(inspection));
        _isCompatible = StringComparer.Ordinal.Equals(
            Inspection.ArchiveVersion,
            AssetArchive.CurrentVersion);
        _migrationAction = "No migration required; runic.assets.archive/1 is retained byte-for-byte.";
    }

    /// <summary>Gets the validated archive inspection.</summary>
    public AssetArchiveInspection Inspection { get; }

    /// <summary>Gets whether this reader accepts the inspected archive schema.</summary>
    public bool IsCompatible => _isCompatible;

    /// <summary>Gets whether migration is required. Retained schema 1 always returns false.</summary>
    public bool RequiresMigration => !_isCompatible;

    /// <summary>Gets the explicit schema-1 migration decision.</summary>
    public string MigrationAction => _migrationAction;

    /// <summary>Writes a deterministic compatibility report suitable for logs and CI artifacts.</summary>
    public string ToDeterministicReport() =>
        Inspection.ToDeterministicReport() +
        "compatible=" + IsCompatible.ToString().ToLowerInvariant() + '\n' +
        "requiresMigration=" + RequiresMigration.ToString().ToLowerInvariant() + '\n' +
        "migrationAction=" + MigrationAction + '\n';
}

/// <summary>Bounds memory and file counts while reading an untrusted asset archive.</summary>
public sealed class AssetArchiveReadOptions
{
    /// <summary>The maximum compressed archive size accepted in bytes.</summary>
    public long MaxArchiveBytes { get; init; } = 1024L * 1024L * 1024L;

    /// <summary>The maximum decompressed manifest size accepted in bytes.</summary>
    public long MaxManifestBytes { get; init; } = 4L * 1024L * 1024L;

    /// <summary>The maximum number of declared files.</summary>
    public int MaxFileCount { get; init; } = 100_000;

    /// <summary>The maximum combined uncompressed content size accepted in bytes.</summary>
    public long MaxTotalUncompressedBytes { get; init; } = 1024L * 1024L * 1024L;
}

/// <summary>An immutable in-memory source loaded from a Runic Assets archive.</summary>
public sealed class AssetArchiveSource : IAssetSnapshotSource
{
    private readonly IReadOnlyDictionary<string, byte[]> _content;

    internal AssetArchiveSource(AssetManifest manifest, IReadOnlyDictionary<string, byte[]> content)
    {
        Manifest = manifest;
        _content = content;
    }

    /// <inheritdoc />
    public AssetManifest Manifest { get; }

    /// <inheritdoc />
    public ValueTask ValidateAsync(CancellationToken cancellationToken = default)
    {
        foreach (AssetDescriptor descriptor in Manifest.Assets)
        {
            cancellationToken.ThrowIfCancellationRequested();
            using var stream = new MemoryStream(_content[descriptor.RelativePath], writable: false);
            AssetHashing.Verify(descriptor, stream);
        }

        return ValueTask.CompletedTask;
    }

    /// <inheritdoc />
    public ValueTask<Stream> OpenReadAsync(string relativePath, CancellationToken cancellationToken = default)
    {
        ValueTask<AssetReadSnapshot> snapshot = OpenSnapshotAsync(relativePath, cancellationToken);
        if (snapshot.IsCompletedSuccessfully)
        {
            return ValueTask.FromResult(snapshot.Result.Content);
        }

        return OpenStreamAsync(snapshot);
    }

    /// <inheritdoc />
    public ValueTask<AssetReadSnapshot> OpenSnapshotAsync(
        string relativePath,
        CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        string path = AssetPath.Normalize(relativePath);
        if (!_content.TryGetValue(path, out byte[]? content))
        {
            throw new FileNotFoundException("The requested asset is not declared by the archive manifest.", path);
        }

        if (!Manifest.TryGetAsset(path, out AssetDescriptor? descriptor))
        {
            throw new FileNotFoundException("The requested asset is not declared by the archive manifest.", path);
        }

        return ValueTask.FromResult(new AssetReadSnapshot(
            descriptor!,
            new MemoryStream(content, writable: false)));
    }

    private static async ValueTask<Stream> OpenStreamAsync(ValueTask<AssetReadSnapshot> snapshot) =>
        (await snapshot.ConfigureAwait(false)).Content;
}
