<Project>
  <Import Project="../../Directory.Build.props" />
  <PropertyGroup>
    <TargetFramework Condition="'$(TargetFramework)' == '' and '$(TargetFrameworks)' == ''">net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RepositoryUrl Condition="'$(RepositoryUrl)' == ''">https://github.com/Runic-Artifex/runic-desktop</RepositoryUrl>
    <RepositoryType Condition="'$(RepositoryType)' == ''">git</RepositoryType>

    <VersionPrefix Condition="'$(VersionPrefix)' == ''">1.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(VersionSuffix)' == ''">preview.1</VersionSuffix>
    <Authors>RunicArtifex</Authors>
    <Company>RunicArtifex</Company>
    <Copyright>Copyright (c) 2026 Viktor Jannicke</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
</Project>
