// <auto-generated />
import { Schema } from "effect";
import { bridge, defineApplicationBridgeContract, materializeApplicationBridgeContract } from "@runic-artifex/application-bridge";

export type ReloadCustomers = { readonly "_tag": "ReloadCustomers"; };
export const ReloadCustomers: Schema.Schema<ReloadCustomers> = Schema.Struct({ "_tag": Schema.Literal("ReloadCustomers") }).annotations({ identifier: "ReloadCustomers" });
export type ReloadCustomersEncoded = Schema.Schema.Encoded<typeof ReloadCustomers>;

export type SaveCustomer = { readonly "_tag": "SaveCustomer"; readonly "draft": CustomerInput; };
export const SaveCustomer: Schema.Schema<SaveCustomer> = Schema.Struct({ "_tag": Schema.Literal("SaveCustomer"), "draft": Schema.suspend(() => CustomerInput) }).annotations({ identifier: "SaveCustomer" });
export type SaveCustomerEncoded = Schema.Schema.Encoded<typeof SaveCustomer>;

export type ValidateCustomer = { readonly "_tag": "ValidateCustomer"; readonly "draft": CustomerInput; };
export const ValidateCustomer: Schema.Schema<ValidateCustomer> = Schema.Struct({ "_tag": Schema.Literal("ValidateCustomer"), "draft": Schema.suspend(() => CustomerInput) }).annotations({ identifier: "ValidateCustomer" });
export type ValidateCustomerEncoded = Schema.Schema.Encoded<typeof ValidateCustomer>;

export type CustomerRejected = { readonly "_tag": "CustomerRejected"; readonly "code": string; readonly "issues": ReadonlyArray<ValidationIssue>; readonly "message": string; };
export const CustomerRejected: Schema.Schema<CustomerRejected> = Schema.Struct({ "_tag": Schema.Literal("CustomerRejected"), "code": Schema.String, "issues": Schema.Array(Schema.suspend(() => ValidationIssue)), "message": Schema.String }).annotations({ identifier: "CustomerRejected" });
export type CustomerRejectedEncoded = Schema.Schema.Encoded<typeof CustomerRejected>;

export type CustomersChanged = { readonly "_tag": "CustomersChanged"; readonly "snapshot": CustomerSnapshot; };
export const CustomersChanged: Schema.Schema<CustomersChanged> = Schema.Struct({ "_tag": Schema.Literal("CustomersChanged"), "snapshot": Schema.suspend(() => CustomerSnapshot) }).annotations({ identifier: "CustomersChanged" });
export type CustomersChangedEncoded = Schema.Schema.Encoded<typeof CustomersChanged>;

export type CustomerReloaded = { readonly "_tag": "CustomerReloaded"; readonly "snapshot": CustomerSnapshot; };
export const CustomerReloaded: Schema.Schema<CustomerReloaded> = Schema.Struct({ "_tag": Schema.Literal("CustomerReloaded"), "snapshot": Schema.suspend(() => CustomerSnapshot) }).annotations({ identifier: "CustomerReloaded" });
export type CustomerReloadedEncoded = Schema.Schema.Encoded<typeof CustomerReloaded>;

export type DraftValidated = { readonly "_tag": "DraftValidated"; readonly "issues": ReadonlyArray<ValidationIssue>; };
export const DraftValidated: Schema.Schema<DraftValidated> = Schema.Struct({ "_tag": Schema.Literal("DraftValidated"), "issues": Schema.Array(Schema.suspend(() => ValidationIssue)) }).annotations({ identifier: "DraftValidated" });
export type DraftValidatedEncoded = Schema.Schema.Encoded<typeof DraftValidated>;

export type SaveStarted = { readonly "_tag": "SaveStarted"; readonly "operationId": string; readonly "snapshot": CustomerSnapshot; };
export const SaveStarted: Schema.Schema<SaveStarted> = Schema.Struct({ "_tag": Schema.Literal("SaveStarted"), "operationId": Schema.String.pipe(Schema.pattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)), "snapshot": Schema.suspend(() => CustomerSnapshot) }).annotations({ identifier: "SaveStarted" });
export type SaveStartedEncoded = Schema.Schema.Encoded<typeof SaveStarted>;

export type CustomerInput = { readonly "company": string; readonly "email": string; readonly "id": string; readonly "name": string; readonly "version": number; };
export const CustomerInput: Schema.Schema<CustomerInput> = Schema.Struct({ "company": Schema.String.pipe(Schema.minLength(0), Schema.maxLength(1000)), "email": Schema.String.pipe(Schema.minLength(0), Schema.maxLength(1000)), "id": Schema.String.pipe(Schema.pattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)), "name": Schema.String.pipe(Schema.minLength(0), Schema.maxLength(1000)), "version": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(1), Schema.lessThanOrEqualTo(2147483647)) }).annotations({ identifier: "CustomerInput" });
export type CustomerInputEncoded = Schema.Schema.Encoded<typeof CustomerInput>;

export type CustomerRow = { readonly "company": string; readonly "email": string; readonly "id": string; readonly "name": string; readonly "version": number; };
export const CustomerRow: Schema.Schema<CustomerRow> = Schema.Struct({ "company": Schema.String, "email": Schema.String, "id": Schema.String.pipe(Schema.pattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)), "name": Schema.String, "version": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(-2147483648), Schema.lessThanOrEqualTo(2147483647)) }).annotations({ identifier: "CustomerRow" });
export type CustomerRowEncoded = Schema.Schema.Encoded<typeof CustomerRow>;

export type CustomerSnapshot = { readonly "customers": ReadonlyArray<CustomerRow>; readonly "generation": number; readonly "save": SaveState; };
export const CustomerSnapshot: Schema.Schema<CustomerSnapshot> = Schema.Struct({ "customers": Schema.Array(Schema.suspend(() => CustomerRow)), "generation": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(-2147483648), Schema.lessThanOrEqualTo(2147483647)), "save": Schema.suspend(() => SaveState) }).annotations({ identifier: "CustomerSnapshot" });
export type CustomerSnapshotEncoded = Schema.Schema.Encoded<typeof CustomerSnapshot>;

export type SaveState = { readonly "issues": ReadonlyArray<ValidationIssue>; readonly "message": string; readonly "operationId": string | null; readonly "progress": number; readonly "status": string; };
export const SaveState: Schema.Schema<SaveState> = Schema.Struct({ "issues": Schema.Array(Schema.suspend(() => ValidationIssue)), "message": Schema.String, "operationId": Schema.Union(Schema.String.pipe(Schema.pattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)), Schema.Null), "progress": Schema.Int.pipe(Schema.between(-9007199254740991, 9007199254740991)).pipe(Schema.greaterThanOrEqualTo(0), Schema.lessThanOrEqualTo(100)), "status": Schema.String }).annotations({ identifier: "SaveState" });
export type SaveStateEncoded = Schema.Schema.Encoded<typeof SaveState>;

export type ValidationIssue = { readonly "field": string; readonly "message": string; };
export const ValidationIssue: Schema.Schema<ValidationIssue> = Schema.Struct({ "field": Schema.String, "message": Schema.String }).annotations({ identifier: "ValidationIssue" });
export type ValidationIssueEncoded = Schema.Schema.Encoded<typeof ValidationIssue>;

const definition = defineApplicationBridgeContract({
  protocol: {"identity":"runic.examples.customers","version":1},
  csharp: {"contractName":"Customers","namespace":"Runic.Application.Generated"},
  snapshot: CustomerSnapshot,
  commands: [
    bridge.command(ReloadCustomers, { receipt: CustomerReloaded, startsOperation: false, cancellable: false, advancesRevision: false }),
    bridge.command(SaveCustomer, { receipt: SaveStarted, startsOperation: true, cancellable: true, advancesRevision: true }),
    bridge.command(ValidateCustomer, { receipt: DraftValidated, startsOperation: false, cancellable: false, advancesRevision: false }),
  ],
  events: [CustomersChanged],
  errors: [CustomerRejected],
});
export const applicationBridge = materializeApplicationBridgeContract(definition, "16401a37d518255343bdaba2603ad228a9464b536dff2e2ab2fd3cd4af5c2775");
export type CustomersCommand = Schema.Schema.Type<typeof applicationBridge.command>;
export type CustomersReceipt = Schema.Schema.Type<typeof applicationBridge.receipt>;
export type CustomersEvent = Schema.Schema.Type<typeof applicationBridge.event>;
export default applicationBridge;
