// <auto-generated />
import { Schema } from "effect";
import { bridge, defineApplicationBridgeContract, materializeApplicationBridgeContract } from "@runic-artifex/application-bridge";

export type OpenDocument = { readonly "_tag": "OpenDocument"; readonly "revision": number; };
export const OpenDocument: Schema.Codec<OpenDocument> = Schema.Struct({ "_tag": Schema.Literal("OpenDocument"), "revision": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(0)), Schema.check(Schema.isLessThanOrEqualTo(2147483647))) }).annotate({ identifier: "OpenDocument" });
export type OpenDocumentEncoded = Schema.Codec.Encoded<typeof OpenDocument>;

export type SaveDocument = { readonly "_tag": "SaveDocument"; readonly "revision": number; readonly "text": string; };
export const SaveDocument: Schema.Codec<SaveDocument> = Schema.Struct({ "_tag": Schema.Literal("SaveDocument"), "revision": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(0)), Schema.check(Schema.isLessThanOrEqualTo(2147483647))), "text": Schema.String.pipe(Schema.check(Schema.isMinLength(0)), Schema.check(Schema.isMaxLength(32768))) }).annotate({ identifier: "SaveDocument" });
export type SaveDocumentEncoded = Schema.Codec.Encoded<typeof SaveDocument>;

export type DocumentRejected = { readonly "_tag": "DocumentRejected"; readonly "code": string; readonly "message": string; };
export const DocumentRejected: Schema.Codec<DocumentRejected> = Schema.Struct({ "_tag": Schema.Literal("DocumentRejected"), "code": Schema.String, "message": Schema.String }).annotate({ identifier: "DocumentRejected" });
export type DocumentRejectedEncoded = Schema.Codec.Encoded<typeof DocumentRejected>;

export type DocumentChanged = { readonly "_tag": "DocumentChanged"; readonly "snapshot": DocumentSnapshot; };
export const DocumentChanged: Schema.Codec<DocumentChanged> = Schema.Struct({ "_tag": Schema.Literal("DocumentChanged"), "snapshot": Schema.suspend(() => DocumentSnapshot) }).annotate({ identifier: "DocumentChanged" });
export type DocumentChangedEncoded = Schema.Codec.Encoded<typeof DocumentChanged>;

export type DocumentStarted = { readonly "_tag": "DocumentStarted"; readonly "operationId": string; readonly "snapshot": DocumentSnapshot; };
export const DocumentStarted: Schema.Codec<DocumentStarted> = Schema.Struct({ "_tag": Schema.Literal("DocumentStarted"), "operationId": Schema.String.check(Schema.isPattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)), "snapshot": Schema.suspend(() => DocumentSnapshot) }).annotate({ identifier: "DocumentStarted" });
export type DocumentStartedEncoded = Schema.Codec.Encoded<typeof DocumentStarted>;

export type DocumentSnapshot = { readonly "capturedRevision": number; readonly "cleanupFailed": boolean; readonly "generation": number; readonly "name": null | string; readonly "operationId": string | null; readonly "status": string; readonly "text": null | string; };
export const DocumentSnapshot: Schema.Codec<DocumentSnapshot> = Schema.Struct({ "capturedRevision": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(-2147483648)), Schema.check(Schema.isLessThanOrEqualTo(2147483647))), "cleanupFailed": Schema.Boolean, "generation": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(-2147483648)), Schema.check(Schema.isLessThanOrEqualTo(2147483647))), "name": Schema.Union([Schema.Null, Schema.String]), "operationId": Schema.Union([Schema.String.check(Schema.isPattern(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/)), Schema.Null]), "status": Schema.String, "text": Schema.Union([Schema.Null, Schema.String]) }).annotate({ identifier: "DocumentSnapshot" });
export type DocumentSnapshotEncoded = Schema.Codec.Encoded<typeof DocumentSnapshot>;

const definition = defineApplicationBridgeContract({
  protocol: {"identity":"runic.examples.documents","version":1},
  csharp: {"contractName":"Documents","namespace":"Runic.Application.Generated"},
  snapshot: DocumentSnapshot,
  commands: [
    bridge.command(OpenDocument, { receipt: DocumentStarted, startsOperation: true, cancellable: true, advancesRevision: true }),
    bridge.command(SaveDocument, { receipt: DocumentStarted, startsOperation: true, cancellable: true, advancesRevision: true }),
  ],
  events: [DocumentChanged],
  errors: [DocumentRejected],
});
export const applicationBridge = materializeApplicationBridgeContract(definition, "bc3aaa1e8ffccc21f5b8123cc53d9dde24d912040dc72014f2d7143c76165bff");
export type DocumentsCommand = Schema.Schema.Type<typeof applicationBridge.command>;
export type DocumentsReceipt = Schema.Schema.Type<typeof applicationBridge.receipt>;
export type DocumentsEvent = Schema.Schema.Type<typeof applicationBridge.event>;
export default applicationBridge;
