using System.ComponentModel;
using Runic.Application.Views;

namespace Runic.Application.Testing.Tests;

// A NavigationRegion<TContent> slot generated by the Bridge build (W230-002 slice 2).
public sealed partial class NavShellWindow(NavShellViewModel model) : RunicWindow<NavShellViewModel>(model);

public sealed partial class NavHomeView : RunicView<NavHomeViewModel>;

public sealed partial class NavEditorView : RunicView<NavEditorViewModel>;

/// <summary>Content of the shell's main region.</summary>
public interface INavPageViewModel : INotifyPropertyChanged
{
    /// <summary>The page title.</summary>
    string Title { get; }
}

public sealed class NavShellViewModel : INotifyPropertyChanged
{
    public NavShellViewModel(RunicNavigator navigator, INavPageViewModel? home = null) =>
        Main = navigator.CreateRegion<INavPageViewModel>(this, home is null ? null : NavigationTarget.Borrow(home));

    /// <summary>The main content; the navigator changes it.</summary>
    public NavigationRegion<INavPageViewModel> Main { get; }

    public event PropertyChangedEventHandler? PropertyChanged { add { } remove { } }
}

public sealed class NavHomeViewModel : INavPageViewModel
{
    public string Title => "home";

    public event PropertyChangedEventHandler? PropertyChanged { add { } remove { } }
}

public sealed class NavEditorViewModel(string title) : INavPageViewModel, IDisposable
{
    private string _draft = "";

    public string Title { get; } = title;

    public string Draft
    {
        get => _draft;
        set { _draft = value; PropertyChanged?.Invoke(this, new(nameof(Draft))); }
    }

    public int Disposed { get; private set; }

    public void Dispose() => Disposed++;

    public event PropertyChangedEventHandler? PropertyChanged;
}

internal sealed class NavViewLocator : IRunicViewLocator
{
    public TView Locate<TView, TViewModel>() where TView : class, IRunicView where TViewModel : class =>
        typeof(TView) == typeof(NavHomeView) ? (TView)(object)new NavHomeView()
        : typeof(TView) == typeof(NavEditorView) ? (TView)(object)new NavEditorView()
        : throw new InvalidOperationException($"Unexpected View {typeof(TView).Name}.");
}
