using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Runic.Application.Bridge.Generators;

public sealed partial class ApplicationBridgeGenerator
{
    private static void EmitMembers(SourceProductionContext context, Compilation compilation, string projectAssemblies)
    {
        if (compilation.GetTypeByMetadataName(MemberBridgeLowerer.Prefix + "BridgeCommandAttribute") is null) return;
        var lowerer = new MemberBridgeLowerer(compilation);
        string? ir = lowerer.Inspect(projectAssemblies.Split(';', StringSplitOptions.RemoveEmptyEntries));
        foreach (Diagnostic diagnostic in lowerer.Errors) context.ReportDiagnostic(diagnostic);
        if (lowerer.Errors.Count != 0) return;
        if (lowerer.Members.Count == 0 && lowerer.Types.Count == 0 && ir is null) return;
        context.AddSource("ApplicationBridge.Module.g.cs", SourceText.From(RenderModule(lowerer), Encoding.UTF8));
        if (ir is not null)
            context.AddSource("ApplicationBridge.Composition.g.cs", SourceText.From(RenderComposition(ir, compilation.GetTypeByMetadataName("Runic.Application.RunicApplicationBridgeCompositionRegistry") is not null), Encoding.UTF8));
    }

    private static string RenderModule(MemberBridgeLowerer lowerer)
    {
        string moduleName = lowerer.Registrar.Split('.').Last();
        string codec = moduleName + "Codec";
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n#pragma warning disable CS1591, CS1998, CA2255\n");
        // Local aliases let the strict codec operate directly on application DTOs.
        var aliases = lowerer.Types.ToDictionary(p => p.Key, p => "Wire_" + MemberBridgeLowerer.Hash(p.Key)[..16], StringComparer.Ordinal);
        foreach (var pair in lowerer.Types.OrderBy(p => p.Key, StringComparer.Ordinal))
            source.Append("using ").Append(aliases[pair.Key]).Append(" = ").Append(pair.Value.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).AppendLine(";");
        source.Append("[assembly: global::Runic.Application.Bridge.BridgeModuleAttribute(").Append(Literal(MemberBridgeLowerer.Canonical(lowerer.Module()))).AppendLine(")]");
        source.AppendLine("namespace Runic.Application.Bridge.Generated {");
        source.Append("internal static class ").Append(codec).AppendLine(" {");
        var definitions = lowerer.Definitions.ToDictionary(p => p.Key, p => JsonDocument.Parse(p.Value!.ToJsonString()).RootElement.Clone(), StringComparer.Ordinal);
        foreach (var pair in lowerer.Types.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            var nested = new List<ObjectModel>();
            ObjectModel model = ParseObject(pair.Key, aliases[pair.Key], definitions[pair.Key], nested, aliases, definitions);
            IPropertySymbol[] properties = MemberBridgeLowerer.Properties(pair.Value).ToArray();
            model = model with {
                Handwritten = true,
                Constructor = lowerer.Constructors[pair.Key].Parameters.Select(p => "@" + properties.Single(prop => string.Equals(prop.Name, p.Name, StringComparison.OrdinalIgnoreCase)).Name).ToImmutableArray(),
                Properties = model.Properties.Select(p => p.JsonName == "_tag" ? p : p with {
                    Name = "@" + properties.Single(prop => MemberBridgeLowerer.JsonName(prop) == p.JsonName).Name,
                    Type = BindType(p.Type, properties.Single(prop => MemberBridgeLowerer.JsonName(prop) == p.JsonName).Type)
                }).ToImmutableArray()
            };
            RenderDecode(source, model); RenderEncode(source, model);
        }
        RenderValidationHelpers(source);
        source.AppendLine("}");
        source.Append("public static class ").Append(moduleName).AppendLine(" {");
        source.AppendLine("    public static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::Runic.Application.Bridge.BridgeModuleRegistry registry) {");
        foreach (INamedTypeSymbol part in lowerer.Members.Select(m => m.Symbol.ContainingType).Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
        {
            IMethodSymbol? constructor = part.InstanceConstructors.Where(c => c.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal).OrderByDescending(c => c.Parameters.Length).FirstOrDefault();
            if (constructor is null) throw new InvalidOperationException("Bridge parts require an accessible constructor.");
            string name = part.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            source.Append("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<").Append(name).Append(">(services, static services => new ").Append(name).Append('(')
                .Append(string.Join(", ", constructor.Parameters.Select(p => "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ">(services)"))).AppendLine("));");
        }
        foreach (var member in lowerer.Members)
        {
            string owner = member.Symbol.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (member.Snapshot) source.Append("        registry.SetSnapshot(static (services, context, cancellationToken) => ");
            else source.Append("        registry.AddCommand(").Append(Literal(member.RequestId![8..])).Append(", static (services, payload, context, cancellationToken) => ");
            source.Append("global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(owner).Append(">(services).").Append(member.Adapter).Append('(')
                .Append(member.Snapshot ? "context, cancellationToken" : "payload, context, cancellationToken").AppendLine("));");
        }
        foreach (var pair in lowerer.Types.Where(p => p.Key.StartsWith("error:", StringComparison.Ordinal)))
            source.Append("        registry.AddError(").Append(Literal(pair.Key[6..])).Append(", static value => ").Append(codec).Append(".Encode").Append(aliases[pair.Key]).Append('(').Append(codec).Append(".Decode").Append(aliases[pair.Key]).AppendLine("(value)));");
        source.AppendLine("    }\n}");
        foreach (var pair in lowerer.Types.Where(p => p.Key.StartsWith("event:", StringComparison.Ordinal) || p.Key.StartsWith("error:", StringComparison.Ordinal)))
        {
            string tag = pair.Key[(pair.Key.IndexOf(':') + 1)..], name = aliases[pair.Key];
            source.Append("internal static class ").Append(moduleName).Append('_').Append(tag).AppendLine("Helpers {");
            if (pair.Key.StartsWith("event:", StringComparison.Ordinal))
                source.Append("    public static global::System.Threading.Tasks.ValueTask Publish").Append(tag).Append("Async(this global::Runic.Application.Bridge.IBridgeEventPublisher publisher, ").Append(name)
                    .Append(" value, bool advancesRevision = false, global::Runic.Application.Bridge.BridgeOperationId? operationId = null, global::System.Threading.CancellationToken cancellationToken = default) => publisher.PublishAsync(new(")
                    .Append(codec).Append(".Encode").Append(name).AppendLine("(value), advancesRevision, operationId), cancellationToken);");
            else source.Append("    public static global::Runic.Application.Bridge.BridgeCommandFailureException ToBridgeError(this ").Append(name).Append(" value) => new(").Append(codec).Append(".Encode").Append(name).AppendLine("(value));");
            source.AppendLine("}");
        }
        source.AppendLine("}");
        foreach (var group in lowerer.Members.GroupBy(m => m.Symbol.ContainingType, SymbolEqualityComparer.Default))
        {
            var type = (INamedTypeSymbol)group.Key!;
            if (!type.ContainingNamespace.IsGlobalNamespace) source.Append("namespace ").Append(type.ContainingNamespace.ToDisplayString()).AppendLine(" {");
            source.Append("partial class @").Append(type.Name).AppendLine(" {");
            foreach (var member in group)
            {
                source.Append("    internal async global::System.Threading.Tasks.ValueTask<").Append(member.Snapshot ? "global::System.Text.Json.JsonElement" : "global::Runic.Application.Bridge.BridgeDispatchResult").Append("> ").Append(member.Adapter).Append('(');
                if (!member.Snapshot) source.Append("global::System.Text.Json.JsonElement payload, ");
                source.Append(member.Snapshot ? "global::Runic.Application.Bridge.BridgeSnapshotContext" : "global::Runic.Application.Bridge.BridgeCommandContext").AppendLine(" context, global::System.Threading.CancellationToken cancellationToken) {");
                if (!member.Snapshot) source.Append("        var command = global::Runic.Application.Bridge.Generated.").Append(codec).Append(".Decode").Append(aliases[member.RequestId!]).AppendLine("(payload);");
                source.Append("        var result = ");
                if (member.Symbol is IMethodSymbol method)
                {
                    bool async = !SymbolEqualityComparer.Default.Equals(method.ReturnType, MemberBridgeLowerer.Unwrap(method.ReturnType));
                    if (async) source.Append("await ");
                    source.Append('@').Append(method.Name).Append('(').Append(string.Join(", ", method.Parameters.Select(p => p.Type.ToDisplayString() == "System.Threading.CancellationToken" ? "cancellationToken" : p.Type.ToDisplayString() is "Runic.Application.Bridge.BridgeCommandContext" or "Runic.Application.Bridge.BridgeSnapshotContext" ? "context" : "command"))).Append(')');
                    if (async) source.Append(".ConfigureAwait(false)");
                }
                else source.Append('@').Append(member.Symbol.Name);
                source.AppendLine(";");
                source.Append("        return "); if (!member.Snapshot) source.Append("new(");
                source.Append("global::Runic.Application.Bridge.Generated.").Append(codec).Append(".Encode").Append(aliases[member.ResultId]).Append("(result)");
                if (!member.Snapshot)
                {
                    source.Append(", ").Append(member.AdvancesRevision ? "true" : "false");
                    if (member.StartsOperation)
                    {
                        string operation = MemberBridgeLowerer.Properties(lowerer.Types[member.ResultId]).Single(p => MemberBridgeLowerer.JsonName(p) == "operationId").Name;
                        source.Append(", new global::Runic.Application.Bridge.BridgeOperationId(result.@").Append(operation).Append("), ").Append(member.Cancellable ? "true" : "false");
                    }
                    source.Append(')');
                }
                source.AppendLine(";\n    }");
            }
            source.AppendLine("}");
            if (!type.ContainingNamespace.IsGlobalNamespace) source.AppendLine("}");
        }
        return source.ToString();
    }

    private static TypeModel BindType(TypeModel model, ITypeSymbol type)
    {
        if (type is INamedTypeSymbol optional && optional.OriginalDefinition.ToDisplayString() == "Runic.Application.Bridge.BridgeOptional<T>") type = optional.TypeArguments[0];
        if (type is INamedTypeSymbol nullable && nullable.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T) type = nullable.TypeArguments[0];
        if (model.Kind == "array")
        {
            ITypeSymbol item = type is IArrayTypeSymbol a ? a.ElementType : ((INamedTypeSymbol)type).TypeArguments[0];
            TypeModel bound = BindType(model.Item!, item);
            return model with { CSharpType = type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), Item = bound };
        }
        if (type.TypeKind == TypeKind.Enum)
            return model with { CSharpType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), Kind = "enum", EnumValues = ((INamedTypeSymbol)type).GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue).Select(f => ("@" + f.Name, Literal(MemberBridgeLowerer.AttrFull(f, "System.Text.Json.Serialization.JsonStringEnumMemberNameAttribute")?.ConstructorArguments[0].Value as string ?? f.Name))).ToImmutableArray() };
        if (model.Kind is "integer" or "number")
        {
            string target = type.WithNullableAnnotation(NullableAnnotation.NotAnnotated).ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return model with { CSharpType = target, NumericCast = target };
        }
        return model;
    }

    private static string RenderComposition(string ir, bool application)
    {
        JsonNode root = JsonNode.Parse(ir)!;
        JsonNode wire = root["wire"]!;
        string name = root["csharp"]!["contractName"]!.GetValue<string>();
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n#pragma warning disable CS1591, CA2255\nnamespace Runic.Application.Generated;\n");
        source.Append("public static class ").Append(name).AppendLine("BridgeContract {");
        source.Append("    public const string ProtocolIdentity = ").Append(Literal(wire["protocol"]!["identity"]!.GetValue<string>())).AppendLine(";");
        source.Append("    public const int ProtocolVersion = ").Append(wire["protocol"]!["version"]).AppendLine(";");
        source.Append("    public const string Fingerprint = ").Append(Literal(root["fingerprint"]!["value"]!.GetValue<string>())).AppendLine(";");
        if (application) source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n    internal static void Register() => global::Runic.Application.RunicApplicationBridgeCompositionRegistry.Register(ConfigureServices, static services => global::Runic.Application.Bridge.ApplicationBridgeSessionFactory.Create(services));");
        source.AppendLine("    public static void ConfigureServices(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services) {");
        source.AppendLine("        var modules = new global::Runic.Application.Bridge.BridgeModuleRegistry();");
        foreach (JsonNode? module in root["bindings"]!["modules"]!.AsArray())
            source.Append("        global::").Append(module!["registrar"]!.GetValue<string>()).AppendLine(".Register(services, modules);");
        source.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::Runic.Application.Bridge.IApplicationBridgeDispatcher>(services, scoped => new global::Runic.Application.Bridge.MemberApplicationBridgeDispatcher(ProtocolIdentity, ProtocolVersion, Fingerprint, scoped, modules));");
        source.AppendLine("    }\n}");
        return source.ToString();
    }

    private static void EmitEffectComposition(SourceProductionContext context, Compilation compilation, ContractModel contract)
    {
        if (compilation.GetTypeByMetadataName("Runic.Application.RunicApplicationBridgeCompositionRegistry") is null) return;
        string handlerInterface = "I" + contract.ContractName + "BridgeHandler";
        INamedTypeSymbol[] handlers = MemberBridgeLowerer.AllTypes(compilation.Assembly.GlobalNamespace)
            .Where(t => !t.IsAbstract && t.DeclaringSyntaxReferences.Any(r => r.GetSyntax() is Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax declaration && declaration.BaseList?.Types.Any(b => b.Type.ToString().Split('.').Last() == handlerInterface) is true)).ToArray();
        if (handlers.Length != 1) return;
        INamedTypeSymbol handler = handlers[0];
        IMethodSymbol? constructor = handler.InstanceConstructors.Where(c => c.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal).OrderByDescending(c => c.Parameters.Length).FirstOrDefault();
        if (constructor is null) return;
        string name = handler.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string dispatcher = "global::" + contract.Namespace + "." + contract.ContractName + "BridgeDispatcher";
        string handlerType = "global::" + contract.Namespace + "." + handlerInterface;
        var source = new StringBuilder("// <auto-generated/>\n#nullable enable\n#pragma warning disable CA2255\nnamespace Runic.Application.Generated;\ninternal static class EffectBridgeComposition {\n");
        source.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer] internal static void Register() => global::Runic.Application.RunicApplicationBridgeCompositionRegistry.Register(Configure, static services => global::Runic.Application.Bridge.ApplicationBridgeSessionFactory.Create(services));");
        source.AppendLine("private static void Configure(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services) {");
        source.Append("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<").Append(handlerType).Append(">(services, static services => new ").Append(name).Append('(')
            .Append(string.Join(", ", constructor.Parameters.Select(p => "global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<" + p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + ">(services)"))).AppendLine("));");
        source.Append("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::Runic.Application.Bridge.IApplicationBridgeDispatcher>(services, static services => new ").Append(dispatcher).Append("(global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<").Append(handlerType).AppendLine(">(services)));");
        source.AppendLine("}\n}");
        context.AddSource("ApplicationBridge.EffectComposition.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Literal(string value) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true);
}
