using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Runic.Application.Tool;

/// <summary>
/// Internal, fixture-only compiled metadata inspection for the post-MVVM discovery
/// experiment. This deliberately has no relationship to the shipping bridge IR.
/// </summary>
internal static class PostMvvmDiscoveryInspection
{
    private const string WindowBase = "Runic.Application.Bridge.PostMvvmFixture.ExplicitWindow`1";
    private const string ViewBase = "Runic.Application.Bridge.PostMvvmFixture.ExplicitView`1";
    private const string ViewBindingAttribute = "Runic.Application.Bridge.PostMvvmFixture.ExplicitViewBindingAttribute";
    private static readonly JsonSerializerOptions Json = new() { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
    private static readonly JsonSerializerOptions CanonicalJson = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    internal static Task<int> RunAsync(string[] args)
    {
        if (args.Length != 10 || args[0] != "--assembly" || args[2] != "--ir" || args[4] != "--esm" || args[6] != "--adapter" || args[8] != "--ready")
            throw new ArgumentException("Post-MVVM discovery requires --assembly <path> --ir <path> --esm <path> --adapter <path> --ready <path>.");

        string assemblyPath = Path.GetFullPath(args[1]);
        string irPath = Path.GetFullPath(args[3]);
        string esmPath = Path.GetFullPath(args[5]);
        string adapterPath = Path.GetFullPath(args[7]);
        string readyPath = Path.GetFullPath(args[9]);
        if (!File.Exists(assemblyPath)) throw new FileNotFoundException("The compiled discovery assembly does not exist.", assemblyPath);
        if (new[] { irPath, esmPath, adapterPath, readyPath }.Distinct(StringComparer.Ordinal).Count() != 4)
            throw new ArgumentException("Post-MVVM output paths must be distinct.");

        // A failed inspection or render must never leave a previously published ready marker.
        File.Delete(readyPath);

        InspectionResult result = Inspect(assemblyPath);
        FixtureRuntime runtime = result.Bindings.Count == 0 ? CreateFixtureRuntime(result) : CreateMappedFixtureRuntime(result);
        // The browser-facing route and wire shape is part of this fixture's
        // discovered contract. Fingerprint it with the member metadata so a
        // ready manifest can never pair an old route map with a new adapter.
        string body = JsonSerializer.Serialize(new IrBody(
            "runic-sdk.post-mvvm-discovery-ir", 1, result.Assembly, result.Views, result.Models, result.Bindings, result.Contracts, runtime), CanonicalJson);
        string fingerprint = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(body))).ToLowerInvariant();

        string ir = JsonSerializer.Serialize(new IrDocument(
            "runic-sdk.post-mvvm-discovery-ir", 1, fingerprint, result.Assembly, result.Views, result.Models, result.Bindings, result.Contracts, runtime), Json);
        string esm = result.Bindings.Count == 0 ? RenderEsm(result, runtime, fingerprint) : RenderMappedEsm(result, runtime, fingerprint);
        string adapter = result.Bindings.Count == 0 ? RenderAdapter(result, fingerprint) : RenderMappedAdapter(result, fingerprint);
        string ready = JsonSerializer.Serialize(new ReadyDocument(
            "runic-sdk.post-mvvm-discovery-ready", 1, fingerprint,
            Path.GetFileName(irPath), Path.GetFileName(esmPath), Path.GetFileName(adapterPath)), Json);

        AtomicWrite(irPath, ir);
        AtomicWrite(esmPath, esm);
        AtomicWrite(adapterPath, adapter);
        AtomicWrite(readyPath, ready);
        Console.WriteLine($"POST_MVVM_SDK_DISCOVERY_EMITTED|views={result.Views.Count}|models={result.Models.Count}|esm=1|adapter=1");
        return Task.FromResult(0);
    }

    private static string RenderMappedEsm(InspectionResult result, FixtureRuntime runtime, string fingerprint)
    {
        ViewContract contract = result.Contracts.Single();
        string bindings = JsonSerializer.Serialize(result.Bindings, CanonicalJson);
        string fields = JsonSerializer.Serialize(contract.Fields, CanonicalJson);
        string routes = JsonSerializer.Serialize(runtime, CanonicalJson);
        string state = String.Join("\n", contract.Fields.Select(field => $"  readonly {field.Name}: string;"));
        return $$"""
            // <auto-generated /> Fixture-only declared View contract and Title wire shape;
            // application selection and mount remain host-owned.
            export const fingerprint = "{{fingerprint}}";
            export const declaredContext = {{JsonSerializer.Serialize(contract.DeclaredContext)}};
            export const bindings = {{bindings}} as const;
            export const fields = {{fields}} as const;
            export const commands = [] as const;
            export const runtime = {{routes}} as const;
            export const routeIds = { titleRead: "titleRead", titleWrite: "titleWrite" } as const;
            export interface ViewContextState {
            {{state}}
            }

            export type TitleReadRequest = Readonly<{ documentEpoch: string; presentationId: string }>;
            export type TitleWriteRequest = Readonly<{ documentEpoch: string; presentationId: string; title: string }>;
            export type TitleReply = Readonly<{ ok: true; title: string }> | Readonly<{ ok: false }>;
            export type TitleRouteId = typeof routeIds[keyof typeof routeIds];

            function exact(value: unknown, fields: readonly { readonly name: string; readonly codec: string }[], context: string): Record<string, unknown> {
              if (value === null || typeof value !== "object" || Array.isArray(value))
                throw new Error(`Invalid ${context}: expected an object.`);
              const object = value as Record<string, unknown>;
              const expected = fields.map(field => field.name).sort();
              const actual = Object.keys(object).sort();
              if (actual.length !== expected.length || actual.some((name, index) => name !== expected[index]))
                throw new Error(`Invalid ${context}: unexpected fields.`);
              for (const field of fields)
                if (typeof object[field.name] !== (field.codec === "boolean" ? "boolean" : "string"))
                  throw new Error(`Invalid ${context}: ${field.name} has the wrong type.`);
              return object;
            }

            function route(id: TitleRouteId) {
              const selected = runtime.routes.find(candidate => candidate.id === id);
              if (!selected) throw new Error(`Unknown declared Title route '${id}'.`);
              return selected;
            }

            export function routeName(referencePrefix: string, id: TitleRouteId): string {
              if (typeof referencePrefix !== "string" || referencePrefix.length === 0)
                throw new Error("A mapped View reference prefix is required.");
              return referencePrefix + route(id).suffix;
            }

            export function encodeTitleRequest(id: "titleRead", value: TitleReadRequest): TitleReadRequest;
            export function encodeTitleRequest(id: "titleWrite", value: TitleWriteRequest): TitleWriteRequest;
            export function encodeTitleRequest(id: TitleRouteId, value: unknown): Record<string, unknown> {
              return exact(value, route(id).request.fields, `${id} request`);
            }

            export function decodeTitleReply(id: TitleRouteId, value: unknown): TitleReply {
              if (value === null || typeof value !== "object" || Array.isArray(value))
                throw new Error(`Invalid ${id} reply: expected an object.`);
              const ok = (value as Record<string, unknown>).ok;
              if (typeof ok !== "boolean") throw new Error(`Invalid ${id} reply: ok must be a boolean.`);
              const variant = route(id).reply.variants.find(candidate => candidate.ok === ok);
              if (!variant) throw new Error(`Invalid ${id} reply: unknown variant.`);
              return exact(value, variant.wire.fields, `${id} reply`) as TitleReply;
            }
            """;
    }

    private static string RenderMappedAdapter(InspectionResult result, string fingerprint)
    {
        ViewContract contract = result.Contracts.Single();
        Field title = contract.Fields.Single(field => field.Name == "title" && field.Writable);
        string models = String.Join("\n", result.Bindings.Select(binding => binding.ConcreteModel).Distinct(StringComparer.Ordinal).Select(model => $$"""
                    internal static string Read{{title.ClrName}}(global::{{model}} model) => model.{{title.ClrName}};
                    internal static void Write{{title.ClrName}}(global::{{model}} model, string value) => model.{{title.ClrName}} = value;
                    internal static global::Runic.Application.Bridge.WindowBridgeAttachment AttachMappedFixtureRoutes(
                        global::Runic.Application.Bridge.IWindowBridgeTransport transport,
                        global::{{model}} model, string route,
                        global::Runic.Application.Bridge.WindowBridgeSession session,
                        global::System.Func<global::Runic.Application.Bridge.WindowBridgeReference> getReference) =>
                        AttachDeclaredTitleRoutes(transport, model, route, session, getReference);
            """));
        return $$"""
            // <auto-generated /> Fixture-only typed projection of the declared interface contract.
            #nullable enable
            namespace Runic.Application.Bridge.PostMvvmFixture.Generated
            {
                public static class PostMvvmDiscoveryAdapter
                {
                    public const string Stage = "post-mvvm-outer";
                    public const string Fingerprint = {{JsonSerializer.Serialize(fingerprint)}};
                    public const string View = {{JsonSerializer.Serialize(contract.View)}};
                    public const string DeclaredContext = {{JsonSerializer.Serialize(contract.DeclaredContext)}};
            {{models}}

                    private static global::Runic.Application.Bridge.WindowBridgeAttachment AttachDeclaredTitleRoutes(
                        global::Runic.Application.Bridge.IWindowBridgeTransport transport,
                        global::{{contract.DeclaredContext}} model, string route,
                        global::Runic.Application.Bridge.WindowBridgeSession session,
                        global::System.Func<global::Runic.Application.Bridge.WindowBridgeReference> getReference)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(transport);
                        global::System.ArgumentNullException.ThrowIfNull(model);
                        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(route);
                        global::System.ArgumentNullException.ThrowIfNull(session);
                        global::System.ArgumentNullException.ThrowIfNull(getReference);
                        var leases = new global::System.Collections.Generic.List<global::Runic.Application.Bridge.WindowBridgeEndpointLease>(2);
                        try
                        {
                            leases.Add(transport.Bind(route + ".{{title.Name}}.read", arguments =>
                            {
                                if (!TryReadTitleRequest(arguments.GetString(), false, out var epoch, out string? presentationId, out _)
                                    || !session.HasPresentation(getReference(), arguments.Connection, epoch!, presentationId!)) return Rejected();
                                return TitlePayload(model.{{title.ClrName}});
                            }));
                            leases.Add(transport.Bind(route + ".{{title.Name}}.write", arguments =>
                            {
                                if (!TryReadTitleRequest(arguments.GetString(), true, out var epoch, out string? presentationId, out string? title)
                                    || !session.HasPresentation(getReference(), arguments.Connection, epoch!, presentationId!)) return Rejected();
                                model.{{title.ClrName}} = title!;
                                return TitlePayload(model.{{title.ClrName}});
                            }));
                            return global::Runic.Application.Bridge.WindowBridgeAttachment.Create(leases.ToArray());
                        }
                        catch
                        {
                            foreach (global::Runic.Application.Bridge.WindowBridgeEndpointLease lease in leases) lease.Dispose();
                            throw;
                        }
                    }

                    private static bool TryReadTitleRequest(string payload, bool write,
                        out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        out string? presentationId, out string? title)
                    {
                        epoch = null;
                        presentationId = title = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (request.ValueKind != global::System.Text.Json.JsonValueKind.Object) return false;
                            var found = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);
                            foreach (global::System.Text.Json.JsonProperty property in request.EnumerateObject())
                                if (!found.Add(property.Name) || (property.Name != "documentEpoch" && property.Name != "presentationId"
                                    && (!write || property.Name != "{{title.Name}}"))) return false;
                            if (found.Count != (write ? 3 : 2)
                                || !request.TryGetProperty("documentEpoch", out var rawEpoch)
                                || rawEpoch.ValueKind != global::System.Text.Json.JsonValueKind.String
                                || !request.TryGetProperty("presentationId", out var rawPresentation)
                                || rawPresentation.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                            presentationId = rawPresentation.GetString();
                            if (global::System.String.IsNullOrWhiteSpace(presentationId) || presentationId.Length > 128) return false;
                            if (write)
                            {
                                if (!request.TryGetProperty("{{title.Name}}", out var rawTitle)
                                    || rawTitle.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                                title = rawTitle.GetString();
                                if (title is null) return false;
                            }
                            epoch = global::Runic.Application.Bridge.WindowBridgeDocumentEpoch.Create(rawEpoch.GetString()!);
                            return true;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                        catch (global::System.ArgumentException) { return false; }
                    }

                    private static string Rejected() => "{\"ok\":false}";

                    private static string TitlePayload(string title)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteBoolean("ok", true);
                            writer.WriteString("{{title.Name}}", title);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }
                }
            }
            """;
    }

    private static FixtureRuntime CreateMappedFixtureRuntime(InspectionResult result)
    {
        ViewContract contract = result.Contracts.Single();
        Field title = contract.Fields.Single(field => field.Name == "title" && field.Writable && field.Codec == "string");
        WireField epoch = new("documentEpoch", "document-epoch");
        WireField presentation = new("presentationId", "string");
        WireField ok = new("ok", "boolean");
        WireField value = new(title.Name, title.Codec);
        return new FixtureRuntime("runic-sdk.post-mvvm-fixture-runtime", 3, "mounted-reference-prefix", [
            new Route("titleRead", contract.DeclaredContext, title.Name, "field-read", "." + title.Name + ".read",
                new WireObject([epoch, presentation]),
                new WireReply([new WireVariant("accepted", true, new WireObject([ok, value])), new WireVariant("rejected", false, new WireObject([ok]))])),
            new Route("titleWrite", contract.DeclaredContext, title.Name, "field-write", "." + title.Name + ".write",
                new WireObject([epoch, presentation, value]),
                new WireReply([new WireVariant("accepted", true, new WireObject([ok, value])), new WireVariant("rejected", false, new WireObject([ok]))])),
        ]);
    }

    private static string RenderEsm(InspectionResult result, FixtureRuntime runtime, string fingerprint)
    {
        Model model = result.Models.Single();
        bool hasCheckedTitleWrite = runtime.Routes.Any(route => route.Id == "titleWriteChecked");
        string snapshotRouteId = hasCheckedTitleWrite ? "\n              titleSnapshot: \"titleSnapshot\"," : String.Empty;
        string checkedRouteId = hasCheckedTitleWrite ? "\n              titleWriteChecked: \"titleWriteChecked\"," : String.Empty;
        string checkedModelRouteId = hasCheckedTitleWrite ? " | typeof routeIds.titleSnapshot | typeof routeIds.titleWriteChecked" : String.Empty;
        string checkedRequestOverload = hasCheckedTitleWrite
            ? "\n            export function encodeRouteRequest(routeId: \"titleWriteChecked\", value: TitleWriteCheckedRequest): TitleWriteCheckedRequest;"
            : String.Empty;
        string snapshotRequestOverload = hasCheckedTitleWrite
            ? "\n            export function encodeRouteRequest(routeId: \"titleSnapshot\", value: TitleReadRequest): TitleReadRequest;"
            : String.Empty;
        string checkedReplyOverload = hasCheckedTitleWrite
            ? "\n            export function decodeRouteReply(routeId: \"titleWriteChecked\", value: unknown): TitleWriteReceipt;"
            : String.Empty;
        string snapshotReplyOverload = hasCheckedTitleWrite
            ? "\n            export function decodeRouteReply(routeId: \"titleSnapshot\", value: unknown): TitleSnapshotReply;"
            : String.Empty;
        string fields = String.Join("\n", model.Fields.Select(field => $"  readonly {field.Name}: string;"));
        string commands = String.Join("\n", model.Commands.Select(command => command.Kind switch
        {
            "toolkit-async-relay" => $"  readonly {command.Name}: () => Promise<void>;",
            "reactive-command-string-string" => $"  readonly {command.Name}: (value: string) => Promise<string>;",
            _ => throw new InvalidOperationException($"Unsupported fixture command {command.Kind}.")
        }));
        string viewMetadata = JsonSerializer.Serialize(result.Views, CanonicalJson);
        string fieldMetadata = JsonSerializer.Serialize(model.Fields, CanonicalJson);
        string commandMetadata = JsonSerializer.Serialize(model.Commands, CanonicalJson);
        string runtimeMetadata = JsonSerializer.Serialize(runtime, CanonicalJson);
        return $$"""
            // <auto-generated /> Internal post-MVVM fixture contract. It describes
            // model-relative and Window-owned routes with strict wire objects;
            // it does not mount a model or resolve an application reference.
            export const fingerprint = "{{fingerprint}}";
            export const views = {{viewMetadata}} as const;
            export const fields = {{fieldMetadata}} as const;
            export const commands = {{commandMetadata}} as const;
            export const runtime = {{runtimeMetadata}} as const;
            export const routeIds = {
              titleRead: "titleRead",
            {{snapshotRouteId}}
              titleWrite: "titleWrite",
            {{checkedRouteId}}
              saveStart: "saveStart",
              saveStatus: "saveStatus",
              saveWait: "saveWait",
              refresh: "refresh",
            } as const;

            export interface ViewModelState {
            {{fields}}
            }

            export interface ViewModelCommands {
            {{commands}}
            }

            export type RuntimeRouteId = typeof routeIds[keyof typeof routeIds];
            export type ModelRouteId = typeof routeIds.titleRead | typeof routeIds.titleWrite{{checkedModelRouteId}} | typeof routeIds.saveStart | typeof routeIds.refresh;
            export type WindowRouteId = typeof routeIds.saveStatus | typeof routeIds.saveWait;
            export type TitleReadRequest = Readonly<{ documentEpoch: string; presentationId: string }>;
            export type TitleWriteRequest = Readonly<{ documentEpoch: string; presentationId: string; title: string }>;
            export type TitleSnapshot = Readonly<{ value: string; version: number; generation: string }>;
            export type TitleSnapshotReply = Readonly<{ ok: true; current: TitleSnapshot }> | Readonly<{ ok: false }>;
            export type TitleWriteCheckedRequest = Readonly<{ documentEpoch: string; presentationId: string; requestId: string; title: string; expected: TitleSnapshot }>;
            export type TitleWriteReceipt =
              | Readonly<{ ok: true; kind: "applied"; current: TitleSnapshot; error: null }>
              | Readonly<{ ok: false; kind: "conflict" | "expired"; current: TitleSnapshot; error: null }>
              | Readonly<{ ok: false; kind: "committed-with-error" | "rejected"; current: TitleSnapshot; error: string }>;
            export type SaveStartRequest = Readonly<{ documentEpoch: string; presentationId: string; requestId: string }>;
            export type SaveObservationRequest = Readonly<{ referenceId: string; documentEpoch: string; requestId: string }>;
            export type RefreshRequest = Readonly<{ documentEpoch: string; presentationId: string; value: string }>;
            export type TitleReply = Readonly<{ ok: true; title: string }> | Readonly<{ ok: false }>;
            export type OperationKind = "unknown" | "running" | "succeeded" | "failed" | "cancelled" | "rejected" | "expired";
            export type SaveStatusReply = Readonly<{ requestId: string | null; kind: OperationKind; state: string | null; error: string | null }>;
            export type SaveStartReply = SaveStatusReply & Readonly<{ accepted: boolean }>;
            export type RefreshReply = Readonly<{ ok: true; value: string }> | Readonly<{ ok: false }>;

            type WireObject = Record<string, unknown>;

            function route(routeId: RuntimeRouteId) {
              const selected = runtime.routes.find(candidate => candidate.id === routeId);
              if (!selected) throw new Error(`Unknown generated route '${routeId}'.`);
              return selected;
            }

            function object(value: unknown, context: string): WireObject {
              if (value === null || typeof value !== "object" || Array.isArray(value))
                throw new Error(`Invalid ${context}: expected an object.`);
              return value as WireObject;
            }

            function exact(value: WireObject, fields: readonly { readonly name: string; readonly codec: string }[], context: string): WireObject {
              const expected = fields.map(field => field.name).sort();
              const actual = Object.keys(value).sort();
              if (actual.length !== expected.length || actual.some((key, index) => key !== expected[index]))
                throw new Error(`Invalid ${context}: unexpected fields.`);
              for (const field of fields) {
                const current = value[field.name];
                if (field.codec === "boolean" ? typeof current !== "boolean"
                    : field.codec === "nullable-string" ? current !== null && typeof current !== "string"
                    : field.codec === "operation-kind" ? !["unknown", "running", "succeeded", "failed", "cancelled", "rejected", "expired"].includes(current as string)
                    : field.codec === "title-write-kind" ? !["applied", "conflict", "expired", "committed-with-error", "rejected"].includes(current as string)
                    : field.codec === "title-snapshot" ? !titleSnapshot(current)
                    : typeof current !== "string")
                  throw new Error(`Invalid ${context}: ${field.name} has the wrong type.`);
              }
              return value;
            }

            function titleSnapshot(value: unknown): value is TitleSnapshot {
              if (value === null || typeof value !== "object" || Array.isArray(value)) return false;
              const record = value as Record<string, unknown>;
              return Object.keys(record).length === 3 && typeof record.value === "string"
                && typeof record.version === "number" && Number.isSafeInteger(record.version) && record.version >= 0
                && typeof record.generation === "string" && /^[0-9a-f]{32}$/.test(record.generation);
            }

            export function routeName(referencePrefix: string, routeId: ModelRouteId): string {
              if (typeof referencePrefix !== "string" || referencePrefix.length === 0)
                throw new Error("A generated route reference prefix is required.");
              const selected = route(routeId);
              if (selected.scope !== "model") throw new Error("A Window route cannot use a model reference prefix.");
              return referencePrefix + selected.suffix;
            }

            export function windowRouteName(routeId: WindowRouteId): string {
              const selected = route(routeId);
              if (selected.scope !== "window") throw new Error("A model route cannot use a Window route name.");
              return selected.suffix;
            }

            export function encodeRouteRequest(routeId: "titleRead", value: TitleReadRequest): TitleReadRequest;
            {{snapshotRequestOverload}}
            export function encodeRouteRequest(routeId: "titleWrite", value: TitleWriteRequest): TitleWriteRequest;
            {{checkedRequestOverload}}
            export function encodeRouteRequest(routeId: "saveStart", value: SaveStartRequest): SaveStartRequest;
            export function encodeRouteRequest(routeId: "saveStatus" | "saveWait", value: SaveObservationRequest): SaveObservationRequest;
            export function encodeRouteRequest(routeId: "refresh", value: RefreshRequest): RefreshRequest;
            export function encodeRouteRequest(routeId: RuntimeRouteId, value: unknown): WireObject {
              return exact(object(value, `${routeId} request`), route(routeId).request.fields, `${routeId} request`);
            }

            export function decodeRouteReply(routeId: "titleRead" | "titleWrite", value: unknown): TitleReply;
            {{snapshotReplyOverload}}
            {{checkedReplyOverload}}
            export function decodeRouteReply(routeId: "saveStart", value: unknown): SaveStartReply;
            export function decodeRouteReply(routeId: "saveStatus" | "saveWait", value: unknown): SaveStatusReply;
            export function decodeRouteReply(routeId: "refresh", value: unknown): RefreshReply;
            export function decodeRouteReply(routeId: RuntimeRouteId, value: unknown): WireObject {
              const reply = object(value, `${routeId} reply`);
              if (routeId === routeIds.saveStart || routeId === routeIds.saveStatus || routeId === routeIds.saveWait)
                return exact(reply, route(routeId).reply.variants[0].wire.fields, `${routeId} reply`);
              if (typeof reply.ok !== "boolean") throw new Error(`Invalid ${routeId} reply: ok must be a boolean.`);
              const variant = route(routeId).reply.variants.find(candidate => candidate.ok === reply.ok);
              if (!variant) throw new Error(`Invalid ${routeId} reply: unknown variant.`);
              return exact(reply, variant.wire.fields, `${routeId} reply`);
            }
            """;
    }

    private static FixtureRuntime CreateFixtureRuntime(InspectionResult result)
    {
        Model model = result.Models.Single();
        Field title = model.Fields.Single(field => field.Name == "title" && field.Codec == "string");
        Command save = model.Commands.Single(command => command.Kind == "toolkit-async-relay");
        Command refresh = model.Commands.Single(command => command.Kind == "reactive-command-string-string");
        WireField documentEpoch = new("documentEpoch", "document-epoch");
        WireField referenceId = new("referenceId", "string");
        WireField presentationId = new("presentationId", "string");
        WireField ok = new("ok", "boolean");
        WireField titleField = new(title.Name, title.Codec);
        WireField value = new("value", "string");
        WireField requestId = new("requestId", "nullable-string");
        WireField kind = new("kind", "operation-kind");
        WireField state = new("state", "nullable-string");
        WireField error = new("error", "nullable-string");
        WireField accepted = new("accepted", "boolean");
        WireField expected = new("expected", "title-snapshot");
        WireField current = new("current", "title-snapshot");
        WireField writeKind = new("kind", "title-write-kind");
        return new FixtureRuntime("runic-sdk.post-mvvm-fixture-runtime", 3, "mounted-reference-prefix", [
            new Route("titleRead", model.Name, title.Name, "field-read", "." + title.Name + ".read",
                new WireObject([documentEpoch, presentationId]),
                new WireReply([new WireVariant("accepted", true, new WireObject([ok, titleField])), new WireVariant("rejected", false, new WireObject([ok]))])),
            new Route("titleSnapshot", model.Name, title.Name, "field-snapshot", "." + title.Name + ".snapshot",
                new WireObject([documentEpoch, presentationId]),
                new WireReply([new WireVariant("accepted", true, new WireObject([ok, current])), new WireVariant("rejected", false, new WireObject([ok]))])),
            new Route("titleWrite", model.Name, title.Name, "field-write", "." + title.Name + ".write",
                new WireObject([documentEpoch, presentationId, titleField]),
                new WireReply([new WireVariant("accepted", true, new WireObject([ok, titleField])), new WireVariant("rejected", false, new WireObject([ok]))])),
            new Route("titleWriteChecked", model.Name, title.Name, "field-write-checked", "." + title.Name + ".writeChecked",
                new WireObject([documentEpoch, presentationId, new WireField("requestId", "string"), titleField, expected]),
                new WireReply([
                    new WireVariant("applied", true, new WireObject([ok, writeKind, current, error])),
                    new WireVariant("conflict", false, new WireObject([ok, writeKind, current, error])),
                    new WireVariant("expired", false, new WireObject([ok, writeKind, current, error])),
                    new WireVariant("committed-with-error", false, new WireObject([ok, writeKind, current, error])),
                    new WireVariant("rejected", false, new WireObject([ok, writeKind, current, error]))])),
            new Route("saveStart", model.Name, save.Name, save.Kind + "-admission", ".save.start",
                new WireObject([documentEpoch, presentationId, new WireField("requestId", "string")]),
                new WireReply([new WireVariant("receipt", null, new WireObject([accepted, requestId, kind, state, error]))])),
            new Route("saveStatus", model.Name, save.Name, save.Kind + "-status", "postmvvm.save.status",
                new WireObject([referenceId, documentEpoch, new WireField("requestId", "string")]),
                new WireReply([new WireVariant("status", null, new WireObject([requestId, kind, state, error]))]), "window"),
            new Route("saveWait", model.Name, save.Name, save.Kind + "-wait", "postmvvm.save.wait",
                new WireObject([referenceId, documentEpoch, new WireField("requestId", "string")]),
                new WireReply([new WireVariant("terminal", null, new WireObject([requestId, kind, state, error]))]), "window"),
            new Route("refresh", model.Name, refresh.Name, refresh.Kind, ".refresh",
                new WireObject([documentEpoch, presentationId, value]),
                new WireReply([new WireVariant("accepted", true, new WireObject([ok, value])), new WireVariant("rejected", false, new WireObject([ok]))])),
        ]);
    }

    private static string RenderAdapter(InspectionResult result, string fingerprint)
    {
        Model model = result.Models.Single();
        string modelType = "global::" + model.Name;
        string window = result.Views.Single(view => view.Kind == "window").Name;
        string view = result.Views.Single(candidate => candidate.Kind == "view").Name;
        string fields = String.Join(",", model.Fields.Select(field => field.Name + ":" + field.Codec));
        string commands = String.Join(",", model.Commands.Select(command => command.Name + ":" + command.Kind));
        Field title = model.Fields.Single(field => field.Name == "title");
        Command save = model.Commands.Single(command => command.Kind == "toolkit-async-relay");
        Command refresh = model.Commands.Single(command => command.Kind == "reactive-command-string-string");
        string accessors = String.Join("\n", model.Fields.Select(field => $$"""
                    internal static string Read{{field.ClrName}}({{modelType}} model) => model.{{field.ClrName}};
                    internal static void Write{{field.ClrName}}({{modelType}} model, string value) => model.{{field.ClrName}} = value;
            """).Concat(model.Commands.Select(command => command.Kind switch
        {
            "toolkit-async-relay" => $$"""
                    internal static global::System.Threading.Tasks.Task Invoke{{command.ClrName}}Async({{modelType}} model) => model.{{command.ClrName}}.ExecuteAsync(null);
                """,
            "reactive-command-string-string" => $$"""
                    internal static global::System.Threading.Tasks.Task<string> Invoke{{command.ClrName}}Async({{modelType}} model, string value) =>
                        global::ReactiveUI.Primitives.Signals.Signal.ToTask(model.{{command.ClrName}}.Execute(value), global::System.Threading.CancellationToken.None);
                """,
            _ => throw new InvalidOperationException($"Unsupported fixture command {command.Kind}.")
        })));
        return $$"""
            // <auto-generated /> Fixture-only typed projection and route adapter; it has no public API commitment.
            #nullable enable
            namespace Runic.Application.Bridge.PostMvvmFixture.Generated
            {
                public static class PostMvvmDiscoveryAdapter
                {
                    public const string Stage = "post-mvvm-outer";
                    public const string Fingerprint = {{JsonSerializer.Serialize(fingerprint)}};
                    public const string Window = {{JsonSerializer.Serialize(window)}};
                    public const string View = {{JsonSerializer.Serialize(view)}};
                    public const string Model = {{JsonSerializer.Serialize(model.Name)}};
                    public const string Fields = {{JsonSerializer.Serialize(fields)}};
                    public const string Commands = {{JsonSerializer.Serialize(commands)}};
                    public const string WindowSaveStatusRoute = "postmvvm.save.status";
                    public const string WindowSaveWaitRoute = "postmvvm.save.wait";

            {{accessors}}

                    // This deliberately has the fixture's fixed route shape. A future application
                    // surface must choose its own generated naming and versioned wire contract.
                    internal static global::Runic.Application.Bridge.WindowBridgeAttachment AttachFixtureRoutes(
                        global::Runic.Application.Bridge.IWindowBridgeTransport transport,
                        {{modelType}} model,
                        string route,
                        global::Runic.Application.Bridge.WindowBridgeSession session,
                        global::System.Func<global::Runic.Application.Bridge.WindowBridgeReference> getReference,
                        global::System.Func<global::Runic.Application.Bridge.WindowBridgeConnection,
                            global::Runic.Application.Bridge.WindowBridgeDocumentEpoch, string, bool> isPresentationMounted,
                        global::System.Action publishTitleInvalidation)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(transport);
                        global::System.ArgumentNullException.ThrowIfNull(model);
                        global::System.ArgumentException.ThrowIfNullOrWhiteSpace(route);
                        global::System.ArgumentNullException.ThrowIfNull(session);
                        global::System.ArgumentNullException.ThrowIfNull(getReference);
                        global::System.ArgumentNullException.ThrowIfNull(isPresentationMounted);
                        global::System.ArgumentNullException.ThrowIfNull(publishTitleInvalidation);
                        var checked{{title.ClrName}} = new global::Runic.Application.Bridge.PostMvvmFixture.FixtureCheckedTitleField(
                            () => Read{{title.ClrName}}(model), value => Write{{title.ClrName}}(model, value));
                        var leases = new global::System.Collections.Generic.List<global::Runic.Application.Bridge.WindowBridgeEndpointLease>(7);
                        try
                        {
                            // The stable CS-WebUI dispatcher publishes through a live endpoint.
                            // This route is outbound-only for the fixture; inbound calls reject.
                            leases.Add(transport.Bind(route + ".{{title.Name}}.changed", _ => FixtureRejected()));
                            leases.Add(transport.Bind(route + ".{{title.Name}}.read", arguments =>
                                TryReadPresentation(arguments.GetString(), out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch, out string? presentationId)
                                    && isPresentationMounted(arguments.Connection, epoch, presentationId)
                                    ? FixtureTitlePayload(Read{{title.ClrName}}(model), includeOk: true)
                                    : FixtureRejected()));
                            leases.Add(transport.Bind(route + ".{{title.Name}}.snapshot", arguments =>
                                TryReadPresentation(arguments.GetString(), out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch, out string? presentationId)
                                    && isPresentationMounted(arguments.Connection, epoch, presentationId)
                                    ? FixtureTitleSnapshotPayload(checked{{title.ClrName}}.Snapshot())
                                    : FixtureRejected()));
                            leases.Add(transport.Bind(route + ".{{title.Name}}.write", arguments =>
                            {
                                if (!TryRead{{title.ClrName}}Write(arguments.GetString(), out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                                    out string? presentationId, out string? value)
                                    || !isPresentationMounted(arguments.Connection, epoch, presentationId)) return FixtureRejected();
                                checked{{title.ClrName}}.SetDirect(value);
                                return FixtureTitlePayload(Read{{title.ClrName}}(model), includeOk: true);
                            }));
                            leases.Add(transport.Bind(route + ".{{title.Name}}.writeChecked", arguments =>
                            {
                                if (!TryRead{{title.ClrName}}CheckedWrite(arguments.GetString(), out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                                    out string? presentationId, out string? requestId, out string? value,
                                    out global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleBaseline? expected)
                                    || !isPresentationMounted(arguments.Connection, epoch, presentationId)) return FixtureTitleReceiptRejected();
                                return FixtureTitleReceiptPayload(checked{{title.ClrName}}.Write(requestId, expected, value));
                            }));
                            // Admission is exact-presentation scoped. It captures the model command as
                            // window-owned work, so unmounting this component cannot replay or cancel it.
                            leases.Add(transport.Bind(route + ".save.start", arguments =>
                            {
                                if (!TryReadSaveStart(arguments.GetString(), out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                                    out string? presentationId, out string? requestId)) return FixtureSaveAdmissionRejected();
                                global::Runic.Application.Bridge.WindowBridgeConnection connection = arguments.Connection;
                                global::Runic.Application.Bridge.WindowBridgeReference reference = getReference();
                                global::Runic.Application.Bridge.WindowBridgeOperationAcceptance acceptance = session.StartOperationFromPresentation(
                                    reference, connection, epoch, presentationId, requestId,
                                    async cancellationToken =>
                                    {
                                        cancellationToken.ThrowIfCancellationRequested();
                                        await Invoke{{save.ClrName}}Async(model).ConfigureAwait(false);
                                        return global::Runic.Application.Bridge.WindowBridgeOperationResult.Succeeded();
                                    }, _ => isPresentationMounted(connection, epoch, presentationId)
                                        ? FixtureSaveState(model)
                                        : null!);
                                return FixtureSaveAdmissionPayload(acceptance);
                            }));
                            leases.Add(transport.BindAsync(route + ".refresh", async (arguments, _) =>
                            {
                                if (!TryReadRefresh(arguments.GetString(), out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                                    out string? presentationId, out string? value)
                                    || !isPresentationMounted(arguments.Connection, epoch, presentationId)) return FixtureRejected();
                                string result = await Invoke{{refresh.ClrName}}Async(model, value).ConfigureAwait(false);
                                return FixtureRefreshPayload(result);
                            }));
                            global::System.IDisposable observation = ObserveFixture{{title.ClrName}}(model, publishTitleInvalidation);
                            return global::Runic.Application.Bridge.WindowBridgeAttachment.Create(observation, leases.ToArray());
                        }
                        catch
                        {
                            foreach (global::Runic.Application.Bridge.WindowBridgeEndpointLease lease in leases) lease.Dispose();
                            throw;
                        }
                    }

                    // The Window owns observation of accepted work after its initiating View
                    // retires. Bind this once in the host's Window scope, outside the model
                    // attachment. The explicit reference selector is checked before the core
                    // document/connection ownership check; neither route admits new work.
                    internal static global::Runic.Application.Bridge.WindowBridgeAttachment BindWindowOperationRoutes(
                        global::Runic.Application.Bridge.IWindowBridgeTransport transport,
                        global::Runic.Application.Bridge.WindowBridgeSession session,
                        global::System.Func<global::Runic.Application.Bridge.WindowBridgeReference> getReference)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(transport);
                        global::System.ArgumentNullException.ThrowIfNull(session);
                        global::System.ArgumentNullException.ThrowIfNull(getReference);
                        var leases = new global::System.Collections.Generic.List<global::Runic.Application.Bridge.WindowBridgeEndpointLease>(2);
                        try
                        {
                            leases.Add(transport.Bind(WindowSaveStatusRoute, arguments =>
                            {
                                if (!TryReadWindowSaveObservation(arguments.GetString(), out string? referenceId,
                                    out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch, out string? requestId))
                                    return FixtureOperationRejected();
                                global::Runic.Application.Bridge.WindowBridgeReference reference = getReference();
                                if (!global::System.String.Equals(referenceId, reference.Id, global::System.StringComparison.Ordinal)
                                    || !session.IsCurrentDocument(arguments.Connection, epoch)) return FixtureOperationRejected();
                                return FixtureOperationStatusPayload(session.LookupOperationFromPresentation(
                                    reference, arguments.Connection, epoch, requestId));
                            }));
                            leases.Add(transport.BindAsync(WindowSaveWaitRoute, async (arguments, cancellationToken) =>
                            {
                                if (!TryReadWindowSaveObservation(arguments.GetString(), out string? referenceId,
                                    out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch, out string? requestId))
                                    return FixtureOperationRejected();
                                global::Runic.Application.Bridge.WindowBridgeReference reference = getReference();
                                if (!global::System.String.Equals(referenceId, reference.Id, global::System.StringComparison.Ordinal)
                                    || !session.IsCurrentDocument(arguments.Connection, epoch)) return FixtureOperationRejected();
                                global::Runic.Application.Bridge.WindowBridgeOperationStatus status = await session.WaitForTerminalFromPresentationAsync(
                                    reference, arguments.Connection, epoch, requestId, cancellationToken).ConfigureAwait(false);
                                return FixtureOperationStatusPayload(status);
                            }));
                            return global::Runic.Application.Bridge.WindowBridgeAttachment.Create(leases.ToArray());
                        }
                        catch
                        {
                            foreach (global::Runic.Application.Bridge.WindowBridgeEndpointLease lease in leases) lease.Dispose();
                            throw;
                        }
                    }

                    internal static global::System.IDisposable ObserveFixture{{title.ClrName}}(
                        {{modelType}} model,
                        global::System.Action publishInvalidation)
                    {
                        global::System.ArgumentNullException.ThrowIfNull(model);
                        global::System.ArgumentNullException.ThrowIfNull(publishInvalidation);
                        global::System.ComponentModel.PropertyChangedEventHandler handler = (_, arguments) =>
                        {
                            if (arguments.PropertyName == nameof(model.{{title.ClrName}})) publishInvalidation();
                        };
                        model.PropertyChanged += handler;
                        return new FixtureRelease(() => model.PropertyChanged -= handler);
                    }

                    private static bool TryReadPresentation(string payload,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? presentationId)
                    {
                        epoch = null;
                        presentationId = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (!TryPresentation(request, out epoch, out presentationId) || !HasOnlyProperties(request, "documentEpoch", "presentationId")) return false;
                            return true;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                    }

                    private static bool TryRead{{title.ClrName}}Write(string payload,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? presentationId,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? value)
                    {
                        epoch = null;
                        presentationId = value = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (!TryPresentation(request, out epoch, out presentationId) || !HasOnlyProperties(request, "documentEpoch", "presentationId", "{{title.Name}}")
                                || !request.TryGetProperty("{{title.Name}}", out global::System.Text.Json.JsonElement field)
                                || field.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                            value = field.GetString();
                            return value is not null;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                    }

                    private static bool TryRead{{title.ClrName}}CheckedWrite(string payload,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? presentationId,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? requestId,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? value,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleBaseline? expected)
                    {
                        epoch = null;
                        presentationId = requestId = value = null;
                        expected = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (!TryPresentation(request, out epoch, out presentationId)
                                || !HasOnlyProperties(request, "documentEpoch", "presentationId", "requestId", "{{title.Name}}", "expected")
                                || !request.TryGetProperty("requestId", out global::System.Text.Json.JsonElement id)
                                || id.ValueKind != global::System.Text.Json.JsonValueKind.String
                                || !request.TryGetProperty("{{title.Name}}", out global::System.Text.Json.JsonElement field)
                                || field.ValueKind != global::System.Text.Json.JsonValueKind.String
                                || !request.TryGetProperty("expected", out global::System.Text.Json.JsonElement baseline)
                                || baseline.ValueKind != global::System.Text.Json.JsonValueKind.Object
                                || !HasOnlyProperties(baseline, "value", "version", "generation")
                                || !baseline.TryGetProperty("value", out global::System.Text.Json.JsonElement baselineValue)
                                || baselineValue.ValueKind != global::System.Text.Json.JsonValueKind.String
                                || !baseline.TryGetProperty("version", out global::System.Text.Json.JsonElement baselineVersion)
                                || !baselineVersion.TryGetInt64(out long version) || version < 0
                                || !baseline.TryGetProperty("generation", out global::System.Text.Json.JsonElement baselineGeneration)
                                || baselineGeneration.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                            requestId = id.GetString();
                            value = field.GetString();
                            string? baselineText = baselineValue.GetString();
                            string? generation = baselineGeneration.GetString();
                            if (string.IsNullOrWhiteSpace(requestId) || requestId.Length > 128 || value is null || baselineText is null
                                || generation is null || !global::System.Guid.TryParseExact(generation, "N", out _)) return false;
                            expected = new global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleBaseline(baselineText, version, generation);
                            return true;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                    }

                    private static bool TryReadSaveStart(string payload,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? presentationId,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? requestId)
                    {
                        epoch = null;
                        presentationId = requestId = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (!TryPresentation(request, out epoch, out presentationId) || !HasOnlyProperties(request, "documentEpoch", "presentationId", "requestId")
                                || !request.TryGetProperty("requestId", out global::System.Text.Json.JsonElement id)
                                || id.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                            requestId = id.GetString();
                            return !string.IsNullOrWhiteSpace(requestId) && requestId.Length <= 128;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                    }

                    private static bool TryReadWindowSaveObservation(string payload,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? referenceId,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? requestId)
                    {
                        referenceId = null;
                        epoch = null;
                        requestId = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (request.ValueKind != global::System.Text.Json.JsonValueKind.Object
                                || !HasOnlyProperties(request, "referenceId", "documentEpoch", "requestId")
                                || !request.TryGetProperty("referenceId", out global::System.Text.Json.JsonElement reference)
                                || reference.ValueKind != global::System.Text.Json.JsonValueKind.String
                                || !request.TryGetProperty("documentEpoch", out global::System.Text.Json.JsonElement documentEpoch)
                                || documentEpoch.ValueKind != global::System.Text.Json.JsonValueKind.String
                                || !request.TryGetProperty("requestId", out global::System.Text.Json.JsonElement id)
                                || id.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                            epoch = global::Runic.Application.Bridge.WindowBridgeDocumentEpoch.Create(documentEpoch.GetString()!);
                            referenceId = reference.GetString();
                            requestId = id.GetString();
                            return !string.IsNullOrWhiteSpace(referenceId) && referenceId.Length <= 128
                                && !string.IsNullOrWhiteSpace(requestId) && requestId.Length <= 128;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                        catch (global::System.ArgumentException) { return false; }
                    }

                    private static bool TryReadRefresh(string payload,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? presentationId,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? value)
                    {
                        epoch = null;
                        presentationId = value = null;
                        try
                        {
                            using global::System.Text.Json.JsonDocument document = global::System.Text.Json.JsonDocument.Parse(payload);
                            global::System.Text.Json.JsonElement request = document.RootElement;
                            if (!TryPresentation(request, out epoch, out presentationId) || !HasOnlyProperties(request, "documentEpoch", "presentationId", "value")
                                || !request.TryGetProperty("value", out global::System.Text.Json.JsonElement argument)
                                || argument.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                            value = argument.GetString();
                            return value is not null;
                        }
                        catch (global::System.Text.Json.JsonException) { return false; }
                    }

                    private static bool TryPresentation(global::System.Text.Json.JsonElement request,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out global::Runic.Application.Bridge.WindowBridgeDocumentEpoch? epoch,
                        [global::System.Diagnostics.CodeAnalysis.NotNullWhen(true)] out string? presentationId)
                    {
                        epoch = null;
                        presentationId = null;
                        if (request.ValueKind != global::System.Text.Json.JsonValueKind.Object
                            || !request.TryGetProperty("documentEpoch", out global::System.Text.Json.JsonElement document)
                            || document.ValueKind != global::System.Text.Json.JsonValueKind.String
                            || !request.TryGetProperty("presentationId", out global::System.Text.Json.JsonElement presentation)
                            || presentation.ValueKind != global::System.Text.Json.JsonValueKind.String) return false;
                        presentationId = presentation.GetString();
                        if (string.IsNullOrWhiteSpace(presentationId) || presentationId.Length > 128) return false;
                        try { epoch = global::Runic.Application.Bridge.WindowBridgeDocumentEpoch.Create(document.GetString()!); }
                        catch (global::System.ArgumentException) { return false; }
                        return true;
                    }

                    private static bool HasOnlyProperties(global::System.Text.Json.JsonElement request, params string[] names)
                    {
                        var found = new global::System.Collections.Generic.HashSet<string>(global::System.StringComparer.Ordinal);
                        foreach (global::System.Text.Json.JsonProperty property in request.EnumerateObject())
                            if (!found.Add(property.Name) || global::System.Array.IndexOf(names, property.Name) < 0) return false;
                        return found.Count == names.Length;
                    }

                    private static string FixtureRejected() => "{\"ok\":false}";

                    private static string FixtureTitleReceiptRejected() =>
                        "{\"ok\":false,\"kind\":\"rejected\",\"current\":{\"value\":\"\",\"version\":0,\"generation\":\"00000000000000000000000000000000\"},\"error\":\"The checked title request is invalid.\"}";

                    private static string FixtureTitleSnapshotPayload(global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleSnapshot snapshot)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteBoolean("ok", true);
                            writer.WritePropertyName("current");
                            WriteTitleSnapshot(writer, snapshot);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private static void WriteTitleSnapshot(global::System.Text.Json.Utf8JsonWriter writer,
                        global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleSnapshot snapshot)
                    {
                        writer.WriteStartObject();
                        writer.WriteString("value", snapshot.Value);
                        writer.WriteNumber("version", snapshot.Version);
                        writer.WriteString("generation", snapshot.Generation);
                        writer.WriteEndObject();
                    }

                    private static string FixtureTitleReceiptPayload(global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleReceipt receipt)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteBoolean("ok", receipt.Kind == global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleWriteKind.Applied);
                            writer.WriteString("kind", receipt.Kind switch
                            {
                                global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleWriteKind.Applied => "applied",
                                global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleWriteKind.Conflict => "conflict",
                                global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleWriteKind.Expired => "expired",
                                global::Runic.Application.Bridge.PostMvvmFixture.FixtureTitleWriteKind.CommittedWithError => "committed-with-error",
                                _ => "rejected",
                            });
                            writer.WritePropertyName("current");
                            WriteTitleSnapshot(writer, receipt.Current);
                            if (receipt.Error is null) writer.WriteNull("error"); else writer.WriteString("error", receipt.Error);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private static string FixtureSaveAdmissionRejected() =>
                        "{\"accepted\":false,\"requestId\":null,\"kind\":\"rejected\",\"state\":null,\"error\":\"The Save admission request is invalid.\"}";

                    private static string FixtureOperationRejected() =>
                        "{\"requestId\":null,\"kind\":\"rejected\",\"state\":null,\"error\":\"The Save observation request is invalid.\"}";

                    private static string FixtureSaveAdmissionPayload(global::Runic.Application.Bridge.WindowBridgeOperationAcceptance acceptance)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteBoolean("accepted", acceptance.Accepted);
                            writer.WriteString("requestId", acceptance.RequestId);
                            WriteOperationStatus(writer, acceptance.Status);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private static string FixtureOperationStatusPayload(global::Runic.Application.Bridge.WindowBridgeOperationStatus status)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteString("requestId", status.RequestId);
                            WriteOperationStatus(writer, status);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private static void WriteOperationStatus(global::System.Text.Json.Utf8JsonWriter writer,
                        global::Runic.Application.Bridge.WindowBridgeOperationStatus status)
                    {
                        writer.WriteString("kind", status.Kind.ToString().ToLowerInvariant());
                        if (status.State is null) writer.WriteNull("state"); else writer.WriteString("state", status.State);
                        if (status.Error is null) writer.WriteNull("error"); else writer.WriteString("error", status.Error);
                    }

                    private static string FixtureSaveState({{modelType}} model)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteNumber("saves", model.SaveCount);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private static string FixtureTitlePayload(string value, bool includeOk)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            if (includeOk) writer.WriteBoolean("ok", true);
                            writer.WriteString("{{title.Name}}", value);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private static string FixtureRefreshPayload(string value)
                    {
                        var bytes = new global::System.Buffers.ArrayBufferWriter<byte>();
                        using (var writer = new global::System.Text.Json.Utf8JsonWriter(bytes))
                        {
                            writer.WriteStartObject();
                            writer.WriteBoolean("ok", true);
                            writer.WriteString("value", value);
                            writer.WriteEndObject();
                            writer.Flush();
                        }
                        return global::System.Text.Encoding.UTF8.GetString(bytes.WrittenSpan);
                    }

                    private sealed class FixtureRelease(global::System.Action release) : global::System.IDisposable
                    {
                        private global::System.Action? _release = release;
                        public void Dispose() => global::System.Threading.Interlocked.Exchange(ref _release, null)?.Invoke();
                    }
                }
            }
            """;
    }

    private static InspectionResult Inspect(string assemblyPath)
    {
        using var context = new MetadataLoadContext(new PathAssemblyResolver(MetadataClosure(assemblyPath)));
        Assembly assembly = context.LoadFromAssemblyPath(assemblyPath);
        Type[] types = assembly.GetTypes();
        Candidate[] candidates = types
            .Where(type => type is { IsClass: true, IsAbstract: false })
            .Select(type => Candidate.TryCreate(type))
            .Where(candidate => candidate is not null)
            .Cast<Candidate>()
            .OrderBy(candidate => candidate.Kind, StringComparer.Ordinal)
            .ThenBy(candidate => candidate.Name, StringComparer.Ordinal)
            .ToArray();

        Candidate[] openCandidates = candidates.Where(candidate => candidate.IsOpenGeneric).ToArray();
        if (openCandidates.Length > 0)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM001",
                $"Explicit Window/View candidates must be closed types in this fixture. Open candidates: {Names(openCandidates)}. Close or remove these candidate types.");

        Candidate[] windows = candidates.Where(candidate => candidate.Kind == "window").ToArray();
        Candidate[] views = candidates.Where(candidate => candidate.Kind == "view").ToArray();
        if (views.Length != 1 || windows.Length == 0)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM002",
                $"This fixture requires at least one explicit Window and exactly one explicit View; found windows={windows.Length} [{Names(windows)}], views={views.Length} [{Names(views)}]. Select one View candidate.");

        // An explicitly selected View contract must not change merely because
        // the application adds another Window. The unbound single-Window
        // interface probe below deliberately retains its concrete projection.
        bool hasExplicitBindings = CustomAttributeData.GetCustomAttributes(views[0].ClrType)
            .Any(attribute => attribute.AttributeType.FullName == ViewBindingAttribute);
        if (windows.Length > 1 || hasExplicitBindings)
            return InspectMappedView(assembly, candidates, windows, views[0]);
        if (views.Length != 1)
            throw new InvalidOperationException("The fixture did not have one View.");

        Candidate window = windows[0];
        Candidate view = views[0];
        string modelName = window.DeclaredContext;
        if (!view.ContextType.IsAssignableFrom(window.ContextType))
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM003",
                $"Explicit Window {window.Name} binds {window.DeclaredContext}, but View {view.Name} declares context {view.DeclaredContext}, which does not accept that concrete model. Select a compatible View context for this fixture pair.");

        if (!window.ContextType.IsClass || window.ContextType.IsAbstract || window.ContextType.ContainsGenericParameters || window.ContextType.Assembly != assembly)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM004",
                $"The Window binds {modelName}, which is not one concrete, closed view model class in the compiled fixture assembly. Declare a concrete fixture model on the Window before selecting a compatible View context.");
        Type model = window.ContextType;
        Model discovered = DiscoverModel(model);
        Field[] fields = discovered.Fields.ToArray();
        Command[] commands = discovered.Commands.ToArray();

        if (!fields.Any(field => field.Name == "title") || !commands.Any(command => command.Kind == "toolkit-async-relay") || !commands.Any(command => command.Kind == "reactive-command-string-string"))
            throw new InvalidOperationException("The compiled fixture did not expose the expected CommunityToolkit and ReactiveUI members.");

        return new InspectionResult(
            assembly.GetName().Name ?? throw new InvalidOperationException("The discovery assembly has no name."),
            candidates.Select(candidate => new View(candidate.Kind, candidate.Name, candidate.DeclaredContext, modelName)).ToArray(),
            [new Model(modelName, fields, commands)], [], []);
    }

    private static InspectionResult InspectMappedView(Assembly assembly, Candidate[] candidates, Candidate[] windows, Candidate view)
    {
        if (!view.ContextType.IsInterface)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM002",
                $"Explicit View mapping requires an interface context and selection keys; View {view.Name} declares {view.DeclaredContext}.");

        CustomAttributeData[] declarations = CustomAttributeData.GetCustomAttributes(view.ClrType)
            .Where(attribute => attribute.AttributeType.FullName == ViewBindingAttribute)
            .ToArray();
        if (declarations.Length == 0)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM002",
                $"View {view.Name} has no explicit selection keys. Declare each allowed concrete model on the View.");
        ViewBinding[] bindings = declarations.Select(declaration =>
        {
            if (declaration.ConstructorArguments.Count != 2 || declaration.ConstructorArguments[0].Value is not string key ||
                declaration.ConstructorArguments[1].Value is not Type type)
                throw new InvalidOperationException("The fixture mapping attribute has an invalid compiled shape.");
            return new ViewBinding(view.Name, view.DeclaredContext, key, TypeName(type));
        }).OrderBy(binding => binding.SelectionKey, StringComparer.Ordinal)
          .ThenBy(binding => binding.ConcreteModel, StringComparer.Ordinal).ToArray();

        if (bindings.Any(binding => String.IsNullOrWhiteSpace(binding.SelectionKey)) ||
            bindings.GroupBy(binding => binding.SelectionKey, StringComparer.Ordinal).Any(group => group.Count() != 1))
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM005",
                $"View {view.Name} has blank or duplicate selection keys. Give every allowed concrete model a distinct nonblank key.");

        var windowModels = windows.Select(window => window.DeclaredContext).ToHashSet(StringComparer.Ordinal);
        if (windowModels.Count != windows.Length)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM007",
                $"Windows select the same concrete model for View {view.Name}. Give each Window a distinct model selection in this fixture.");
        foreach (Candidate window in windows)
            if (!window.ContextType.IsClass || window.ContextType.IsAbstract || window.ContextType.ContainsGenericParameters || window.ContextType.Assembly != assembly)
                throw new PostMvvmDiscoveryDiagnosticException("RUNICPM004",
                    $"Window {window.Name} binds {window.DeclaredContext}, which is not a concrete, closed model in the compiled fixture assembly.");

        foreach (ViewBinding binding in bindings)
        {
            Type mapped = assembly.GetType(binding.ConcreteModel) ??
                throw new PostMvvmDiscoveryDiagnosticException("RUNICPM006", $"Selection key {binding.SelectionKey} names a model outside the compiled fixture assembly.");
            if (!mapped.IsClass || mapped.IsAbstract || !view.ContextType.IsAssignableFrom(mapped))
                throw new PostMvvmDiscoveryDiagnosticException("RUNICPM006",
                    $"Selection key {binding.SelectionKey} maps {binding.ConcreteModel}, which does not implement View {view.Name}'s declared context {view.DeclaredContext}.");
        }
        string[] unmapped = windows.Select(window => window.DeclaredContext)
            .Where(model => !bindings.Any(binding => binding.ConcreteModel == model)).ToArray();
        string[] unused = bindings.Select(binding => binding.ConcreteModel)
            .Where(model => !windowModels.Contains(model)).ToArray();
        if (unmapped.Length > 0 || unused.Length > 0)
            throw new PostMvvmDiscoveryDiagnosticException("RUNICPM007",
                $"View {view.Name} mappings do not match Window selections; unmapped [{String.Join(", ", unmapped)}], unused [{String.Join(", ", unused)}]. Declare exactly one selection key for each selected model.");

        Field[] contractFields = view.ContextType.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property.PropertyType.FullName == "System.String" && property.CanRead)
            .Select(property => new Field(ToCamelCase(property.Name), "string", property.CanWrite, property.Name))
            .OrderBy(field => field.Name, StringComparer.Ordinal).ToArray();
        Command[] contractCommands = view.ContextType.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Select(Command.TryCreate).Where(command => command is not null).Cast<Command>()
            .OrderBy(command => command.Name, StringComparer.Ordinal).ToArray();
        if (contractFields.Length != 1 || contractFields[0].Name != "title" || !contractFields[0].Writable || contractCommands.Length != 0)
            throw new InvalidOperationException("The fixture interface must declare only a writable Title and no commands.");

        return new InspectionResult(
            assembly.GetName().Name ?? throw new InvalidOperationException("The discovery assembly has no name."),
            candidates.Select(candidate => new View(candidate.Kind, candidate.Name, candidate.DeclaredContext,
                candidate.Kind == "window" ? candidate.DeclaredContext : null)).ToArray(),
            windows.Select(window => DiscoverModel(window.ContextType)).ToArray(), bindings,
            [new ViewContract(view.Name, view.DeclaredContext, contractFields, contractCommands)]);
    }

    private static Model DiscoverModel(Type model)
    {
        Field[] fields = model.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(property => property is { CanRead: true, CanWrite: true } && property.PropertyType.FullName == "System.String")
            .Select(property => new Field(ToCamelCase(property.Name), "string", true, property.Name))
            .OrderBy(field => field.Name, StringComparer.Ordinal).ToArray();
        Command[] commands = model.GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Select(Command.TryCreate).Where(command => command is not null).Cast<Command>()
            .OrderBy(command => command.Name, StringComparer.Ordinal).ToArray();
        return new Model(TypeName(model), fields, commands);
    }

    private static IEnumerable<string> MetadataClosure(string assemblyPath)
    {
        string directory = Path.GetDirectoryName(assemblyPath) ?? throw new InvalidOperationException("The compiled assembly has no directory.");
        string? trusted = AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES") as string;
        if (String.IsNullOrWhiteSpace(trusted)) throw new InvalidOperationException("The runtime did not expose its trusted platform assembly closure.");
        return Directory.EnumerateFiles(directory, "*.dll")
            .Concat(trusted.Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries))
            .Append(assemblyPath)
            .Distinct(StringComparer.OrdinalIgnoreCase);
    }

    private static string TypeName(Type type) => type.FullName ?? throw new InvalidOperationException("A fixture type has no metadata name.");

    private static string Names(IEnumerable<Candidate> candidates) => String.Join(", ", candidates.Select(candidate => candidate.Name));

    private static string ToCamelCase(string value) => Char.ToLowerInvariant(value[0]) + value[1..];

    private static void AtomicWrite(string path, string content)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? throw new InvalidOperationException("Output path has no directory."));
        string temporary = path + ".tmp";
        File.WriteAllText(temporary, content + Environment.NewLine, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        File.Move(temporary, path, overwrite: true);
    }

    private sealed record InspectionResult(string Assembly, IReadOnlyList<View> Views, IReadOnlyList<Model> Models,
        IReadOnlyList<ViewBinding> Bindings, IReadOnlyList<ViewContract> Contracts);
    private sealed record Candidate(string Kind, string Name, string DeclaredContext, Type ContextType, Type ClrType, bool IsOpenGeneric)
    {
        internal static Candidate? TryCreate(Type type)
        {
            for (Type? current = type.BaseType; current is not null; current = current.BaseType)
            {
                if (!current.IsGenericType) continue;
                string? definition = current.GetGenericTypeDefinition().FullName;
                string kind = definition == WindowBase ? "window" : definition == ViewBase ? "view" : String.Empty;
                if (String.IsNullOrEmpty(kind)) continue;
                Type model = current.GetGenericArguments()[0];
                return new Candidate(kind, TypeName(type), model.FullName ?? model.Name, model, type, type.ContainsGenericParameters || model.ContainsGenericParameters);
            }
            return null;
        }
    }

    private sealed record Field(string Name, string Codec, bool Writable, [property: JsonIgnore] string ClrName);
    private sealed record Command(string Name, string Kind, [property: JsonIgnore] string ClrName)
    {
        internal static Command? TryCreate(PropertyInfo property)
        {
            if (property.PropertyType.FullName == "CommunityToolkit.Mvvm.Input.IAsyncRelayCommand" || property.PropertyType.GetInterfaces().Any(type => type.FullName == "CommunityToolkit.Mvvm.Input.IAsyncRelayCommand"))
                return new Command(ToCamelCase(property.Name), "toolkit-async-relay", property.Name);
            if (property.PropertyType.IsGenericType && property.PropertyType.GetGenericTypeDefinition().FullName == "ReactiveUI.ReactiveCommand`2" &&
                property.PropertyType.GetGenericArguments() is [Type input, Type output] &&
                input.FullName == "System.String" && output.FullName == "System.String")
                return new Command(ToCamelCase(property.Name), "reactive-command-string-string", property.Name);
            return null;
        }
    }

    private sealed record View(string Kind, string Name, string DeclaredContext, string? ConcreteModel);
    private sealed record ViewBinding(string View, string DeclaredContext, string SelectionKey, string ConcreteModel);
    private sealed record ViewContract(string View, string DeclaredContext, IReadOnlyList<Field> Fields, IReadOnlyList<Command> Commands);
    private sealed record Model(string Name, IReadOnlyList<Field> Fields, IReadOnlyList<Command> Commands);
    private sealed record WireField(string Name, string Codec);
    private sealed record WireObject(IReadOnlyList<WireField> Fields);
    private sealed record WireVariant(string Name, bool? Ok, WireObject Wire);
    private sealed record WireReply(IReadOnlyList<WireVariant> Variants);
    private sealed record Route(string Id, string Model, string Member, string Kind, string Suffix, WireObject Request, WireReply Reply, string Scope = "model");
    private sealed record FixtureRuntime(string Format, int FormatVersion, string ReferencePrefix, IReadOnlyList<Route> Routes);
    private sealed record IrBody(string Format, int FormatVersion, string Assembly, IReadOnlyList<View> Views, IReadOnlyList<Model> Models,
        IReadOnlyList<ViewBinding> Bindings, IReadOnlyList<ViewContract> Contracts, FixtureRuntime Runtime);
    private sealed record IrDocument(string Format, int FormatVersion, string Fingerprint, string Assembly, IReadOnlyList<View> Views, IReadOnlyList<Model> Models,
        IReadOnlyList<ViewBinding> Bindings, IReadOnlyList<ViewContract> Contracts, FixtureRuntime Runtime);
    private sealed record ReadyDocument(string Format, int FormatVersion, string Fingerprint, string Ir, string Esm, string Adapter);
}

internal sealed class PostMvvmDiscoveryDiagnosticException(string code, string message) : Exception(message)
{
    internal string Code { get; } = code;
}
