// <auto-generated />
import { Schema } from "effect";
import { bridge, defineApplicationBridgeContract, materializeApplicationBridgeContract } from "@runic-artifex/application-bridge";

export type IncrementCounter = { readonly "_tag": "IncrementCounter"; readonly "step": number; };
export const IncrementCounter: Schema.Codec<IncrementCounter> = Schema.Struct({ "_tag": Schema.Literal("IncrementCounter"), "step": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(1)), Schema.check(Schema.isLessThanOrEqualTo(10))) }).annotate({ identifier: "IncrementCounter" });
export type IncrementCounterEncoded = Schema.Codec.Encoded<typeof IncrementCounter>;

export type ResetCounter = { readonly "_tag": "ResetCounter"; };
export const ResetCounter: Schema.Codec<ResetCounter> = Schema.Struct({ "_tag": Schema.Literal("ResetCounter") }).annotate({ identifier: "ResetCounter" });
export type ResetCounterEncoded = Schema.Codec.Encoded<typeof ResetCounter>;

export type CounterChanged = { readonly "_tag": "CounterChanged"; readonly "snapshot": CounterSnapshot; };
export const CounterChanged: Schema.Codec<CounterChanged> = Schema.Struct({ "_tag": Schema.Literal("CounterChanged"), "snapshot": Schema.suspend(() => CounterSnapshot) }).annotate({ identifier: "CounterChanged" });
export type CounterChangedEncoded = Schema.Codec.Encoded<typeof CounterChanged>;

export type CounterIncremented = { readonly "_tag": "CounterIncremented"; readonly "snapshot": CounterSnapshot; };
export const CounterIncremented: Schema.Codec<CounterIncremented> = Schema.Struct({ "_tag": Schema.Literal("CounterIncremented"), "snapshot": Schema.suspend(() => CounterSnapshot) }).annotate({ identifier: "CounterIncremented" });
export type CounterIncrementedEncoded = Schema.Codec.Encoded<typeof CounterIncremented>;

export type CounterReset = { readonly "_tag": "CounterReset"; readonly "snapshot": CounterSnapshot; };
export const CounterReset: Schema.Codec<CounterReset> = Schema.Struct({ "_tag": Schema.Literal("CounterReset"), "snapshot": Schema.suspend(() => CounterSnapshot) }).annotate({ identifier: "CounterReset" });
export type CounterResetEncoded = Schema.Codec.Encoded<typeof CounterReset>;

export type CounterSnapshot = { readonly "count": number; readonly "history": ReadonlyArray<number>; readonly "revision": number; };
export const CounterSnapshot: Schema.Codec<CounterSnapshot> = Schema.Struct({ "count": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(-2147483648)), Schema.check(Schema.isLessThanOrEqualTo(2147483647))), "history": Schema.Array(Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(-2147483648)), Schema.check(Schema.isLessThanOrEqualTo(2147483647)))), "revision": Schema.Int.check(Schema.isBetween({ minimum: -9007199254740991, maximum: 9007199254740991 })).pipe(Schema.check(Schema.isGreaterThanOrEqualTo(0)), Schema.check(Schema.isLessThanOrEqualTo(9007199254740991))) }).annotate({ identifier: "CounterSnapshot" });
export type CounterSnapshotEncoded = Schema.Codec.Encoded<typeof CounterSnapshot>;

const definition = defineApplicationBridgeContract({
  protocol: {"identity":"runic.artifex.counter","version":1},
  csharp: {"contractName":"Counter","namespace":"Runic.Application.Generated"},
  snapshot: CounterSnapshot,
  commands: [
    bridge.command(IncrementCounter, { receipt: CounterIncremented, startsOperation: false, cancellable: false, advancesRevision: true }),
    bridge.command(ResetCounter, { receipt: CounterReset, startsOperation: false, cancellable: false, advancesRevision: true }),
  ],
  events: [CounterChanged],
  errors: [],
});
export const applicationBridge = materializeApplicationBridgeContract(definition, "58a0dda63c7e4b41ebce179913af55c0e53b5d17d627e8fd7116da40414a11d5");
export type CounterCommand = Schema.Schema.Type<typeof applicationBridge.command>;
export type CounterReceipt = Schema.Schema.Type<typeof applicationBridge.receipt>;
export type CounterEvent = Schema.Schema.Type<typeof applicationBridge.event>;
export default applicationBridge;
