<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicCommandLineDefaultTargetFramework)</TargetFramework>
    <AssemblyName>CommandLine.Kernel</AssemblyName>
    <RootNamespace>Runic.CommandLine.Samples.Kernel</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Runic.CommandLine/Runic.CommandLine.csproj" />
    <ProjectReference Include="../../../src/Runic.CommandLine.Processes/Runic.CommandLine.Processes.csproj" />
  </ItemGroup>
</Project>
