<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(RunicCommandLineDefaultTargetFramework)</TargetFramework>
    <AssemblyName>CommandLine.Kernel</AssemblyName>
    <RootNamespace>RunicCommandLine.Samples.Kernel</RootNamespace>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/RunicCommandLine.Abstractions/RunicCommandLine.Abstractions.csproj" />
    <ProjectReference Include="../../../src/RunicCommandLine/RunicCommandLine.csproj" />
    <ProjectReference Include="../../../src/RunicCommandLine.Processes/RunicCommandLine.Processes.csproj" />
  </ItemGroup>
</Project>
